phil-opp/blog_os

- src/arch/x86_64/long_mode_init.asm
- src/lib.rs
This requires renaming `main` as `cargo test` imports `std`, which defines its own not mangled `main`. Furthermore, the `eh_personality` and `panic_fmt` lang are already implemented by `std`.
> Fix testing

- Cargo.toml
- src/lib.rs
- src/vga_buffer.rs
Adds an module for the VGA text buffer to print to the screen. It supports the standard formatting traits and provides `print!` and `println!` macros. By using interior mutability through a spinlock, it can be safely used from multiple threads simultaneously.
Update main to use the `println!` macro for `Hello World!`.
> Add a VGA buffer module

- src/arch/x86_64/boot.asm
> Use unsigned `mul` instead of signed `imul`

- posts/2015-08-25-entering-longmode.md
I think there is a typo in the section describing how the P2 mapping is set up. The corresponding code sets _P2_'s third entry.
> Fix typo in "Entering long mode"

- posts/2015-08-25-entering-longmode.md
> Small grammar nit in "Entering Longmode" post

- posts/2015-08-25-entering-longmode.md
- src/arch/x86_64/boot.asm
Don't set the `write protect` bit as we don't need it now. Resolves #47 .
> Don't set `write protect` bit when enabling paging

- posts/2015-11-15-allocating-frames.md
- src/memory/area_frame_allocator.rs
- src/memory/mod.rs
If a Frame would be clonable or even Copy, the frame could be freed (e.g. passed to deallocate_frame) and used thereafter. Or it could be freed multiple times.
> Don't derive Copy/Clone for Frame so we can be sure that it's free

- Makefile
- posts/2015-08-18-multiboot-kernel.md
- posts/2015-09-02-setup-rust.md
Warning occurs in QEMU 2.3.0. It looks like this:
```
WARNING: Image format was not specified for 'build/os-x86_64.iso' and probing guessed raw. 
Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted. 
Specify the 'raw' format explicitly to remove the restrictions. 
```
So QEMU does not allow writing to block 0 if we auto detect the image type. It seems like QEMU uses block 0 to perform the autodetection, so writing some random bytes to it could cause an accidental image type change on the next start. See the [QEMU changelog](http://wiki.qemu.org/ChangeLog/2.3#Block_devices_in_system_emulation) for (a bit) more information.
We can fix this by specifying the format explicitely through `format=raw`. Thus the autodetection is disabled …
> Specify `raw` ISO format explicitely to avoid QEMU warning

- posts/2015-08-25-entering-longmode.md
- posts/2015-09-02-set-up-rust.md
- posts/2015-12-09-modifying-page-tables.md
- src/arch/x86_64/boot.asm
`set up` instead of `setup`
Fixes #66
> Fix grammar: `set up` instead of `setup`

- posts/2015-08-25-entering-longmode.md
- src/arch/x86_64/boot.asm
This reverts commit a39a6116298d7222dcf47dac243caa79bc3987a0 and updates the _Entering Longmode_ post.
> Rename `test_*` functions to `check_*` again

- posts/2015-10-23-printing-to-screen.md
previously compile would fail with E0133
> Add unsafe to Unique::new

- Makefile
- pages/set-up-gdb.md
- posts/2015-08-18-multiboot-kernel.md
- posts/2015-09-02-set-up-rust.md
- posts/2016-01-01-remap-the-kernel.md
Right now, it does not matter whether we boot from a drive or a cdrom. Therefore we use the shorter `-cdrom`. Note that `-hda` would generate a warning in newer QEMU versions (see #56).
Fixes #101
> Use `-cdrom` instead of `-drive` as it's shorter

- posts/2015-11-15-allocating-frames.md
Small typos I found while reading and working through your posts. Thanks for the great work. I hope to see more coming, I have been learning a lot from these.
> Fixed typos in post Allocating Frames

- Cargo.toml
- posts/2015-12-09-modifying-page-tables.md
The official `bitflags` crate has a `no_std` feature now.
Closes #110
~~Blocked by rust-lang-nursery/bitflags#34~~
> Use official bitflags crate

- posts/2016-01-01-remap-the-kernel.md
- src/arch/x86_64/linker.ld
- src/memory/paging/mod.rs
This PR adds an “Fixing the Frame Allocator” section to fix #126. It avoids the [multiboot-structure-between-kernel-sections-issue](https://github.com/phil-opp/blog_os/issues/126#issuecomment-176907574) by making the section size a multiple of the page size (instead of only aligning the section _start_ as before).
An alternative to this PR would be to debug and fix it in the upcoming post. The debugging steps could be pretty interesting. But I don't have the time right now and I'm not sure if it's interesting enough for outsiders…
cc @mmalone
**TODO:**
Fixes #126
> Identity map the multiboot structure to fix the frame allocator

- posts/2016-01-01-remap-the-kernel.md
- src/lib.rs
- src/memory/mod.rs
- src/memory/paging/mod.rs
The old code used `range.step_by(PAGE_SIZE)` to iterate over all frames in a section. This was wrong because a section could be smaller than `PAGE_SIZE` but span 2 frames nonetheless. For example: the multiboot section is 1554 bytes and goes from `0x155e60` to `0x156468`. Then the `range.step_by` method would only return the first frame.
The new code adds a `Frame::range_inclusive`, which allows iterating over the frames directly. The post contains an explanation why we avoid [core::ops::Range](https://doc.rust-lang.org/nightly/core/ops/struct.Range.html).
This is a major update, so we set the `updated` tag of _Remap the Kernel_.
> Fix bug in frame iteration

- blog/post/2015-09-02-set-up-rust.md
objdump on my system and code snippet in blog agree - problem is caused
by `movups` not `movaps`. Fix surrounding text and doc link to reflect
this.
> Replace movaps with movups

- blog/post/2015-10-23-printing-to-screen.md
Although minor, I've added some missing `use` statements to the code examples in the VGA buffer entry
> Add missing `use` statements in printing-to-screen

- blog/post/2016-04-11-kernel-heap.md
Reported by @simonlovgren in #160
> Fix: `hole_list_allocator` instead of `linked_list_allocator`

- static/css/poole.css
IMO it looks nicer on Windows :)
> Use the “Consolas” font instead of “Courier New” for code blocks

- Cargo.toml
- Makefile
- blog/post/2015-09-02-set-up-rust.md
- blog/post/2016-04-11-kernel-heap.md
- src/lib.rs
This PR adds the panic=abort profile option to Cargo.toml:
```toml
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
```
This replaces the unstable `-Z no-landing-pads` flag and should work even better (no more `_Unwind_Resume` linker errors in the [Kernel Heap](http://os.phil-opp.com/kernel-heap.html) post).
> Use the `panic=abort` option instead of `-Z no-landing-pads`

- blog/post/2015-09-02-set-up-rust.md
Someone in `#rust-osdev` was following along, and while you no longer use `-Zno-landing-pads`, the title still talked about it. I don't know if you wanted to keep it, or use something else, but here's a suggestion :smile:
> Update section header to reflect changes in the text

- blog/post/2016-01-01-remap-the-kernel.md
- src/arch/x86_64/linker.ld
No longer needed because we use `panic=abort` now.
> Remove unneeded gcc_except_table section

- blog/post/2016-01-01-remap-the-kernel.md
- src/arch/x86_64/linker.ld
I'm not sure why, but sometimes the `gcc_except_table` section keeps popping up (e.g. in b22d4b19901b78be580fc01d8622b48b0083e622).
Reverts phil-opp/blog_os#178
> Revert "Remove unneeded gcc_except_table section"

- blog/post/2016-05-28-catching-exceptions.md
- src/interrupts/mod.rs
- src/lib.rs
The divide error pushes no error code. Thus we avoid stack misalignment.
Fixes #184
> Catch divide error instead of page fault

- blog/post/2015-11-15-allocating-frames.md
The updated linker script shown in the blog post is missing the `ENTRY(start)` line. If a reader replaces their linker script with the one shown, instead of only replacing the `SECTIONS` block, the script will no longer function.
> Add ENTRY(start) to 'Allocating Frames' blog post linker script

- blog/post/2016-01-01-remap-the-kernel.md
- src/arch/x86_64/linker.ld
These sections suddenly appeared on a newer compiler…
> Add aligned .got and .got.plt sections to linker script

- blog/post/2015-08-18-multiboot-kernel.md
`2f4f` and `2f4b` switches places in one places where it's mentioned, I assume this was a typo since all the others looked this way :)
Edit: And, now that I've managed to build the thing (thanks by the way), because `0x2f4b2f4f` is `OK` while the reversed is `KO`
> Fix hex constant

- layouts/partials/head.html
- static/css/main.css
- static/js/main.js
- static/js/toc.min.js
The ToC is displayed through javascript on the left side when the display is large enough:
--
---
The ToC position is fixed so that it doesn't scroll with the rest of the page and remains always at the same place:
--
---
On smaller displays, the ToC is hidden via `display: none`.
Put it on the right side and use absolute instead of fixed positioning:
--
---
Put it before the text, so that it is displayed on all devices.
- Other options?
- Is a ToC too much visual clutter?
- Design improvements?
- Should we also display it on smaller displays?
- Fade the ToC out until the mouse hovers it again?
> Display a Table of Contents on large displays

- blog/post/2016-08-03-better-exception-messages.md
In the second macro (handler_with_error_code), we pop the error code into rsi, this means we are changing the value of rsi in the assembly block, so we should add it to the clobbers.
I am quite new to this, so please close this request if I am completely wrong.
(Side question: An other thing I came across while trying to figure out if this was correct, is that every documentation says you should add curly brackets around register names, can someone tell me why this is not done here?)
> Add rsi to the clobber list

- blog/post/2016-08-03-better-exception-messages.md
I'm not a native speaker so I'm not 100% sure but I guess this "use" shouldn't be there.
> removed extra "use"

- blog/post/2015-12-09-page-tables.md
- blog/post/2016-01-01-remap-the-kernel.md
I am not a native English speaker, so I am not 100% sure this is correct, but from the information I found on https://www.translegal.com/legal-english-lessons/therefore-vs-therefor , it looks like in this case, the word "therefore" is correct.
> Fix typo (therefor -> therefore)

- blog/post/2015-08-25-entering-longmode.md
- blog/post/2015-09-02-set-up-rust.md
- blog/post/2015-12-09-page-tables.md
- blog/post/2016-01-01-remap-the-kernel.md
While going through the posts, I found some small typos:
1. In `boot.asm`, the `start` function was `_start` in one listing,
2. The `Set up Rust` post had an incorrect year of last update (2015 instead of 2016),
3. `unwrap` instead of `unmap` in `Modifying Page Tables`,
4. Changed `reexport` to `re-export` in some cases.
> Fix various typos

- ci/travis-blog-update.sh
- layouts/rss.xml
This PR adds a template file for the main rss feed. Thus we can avoid the hack that we've used before (copy the default feed for the `post` category to the root).
Fixes #211
> Fix atom feed

- layouts/rss.xml
This fixes the breaking change introduced by https://github.com/spf13/hugo/issues/2464
> Use new `.Authors` instead of deprecated `.Author`

- blog/post/08-kernel-heap.md
- libs/bump_allocator/src/lib.rs
I also fixed a spelling error and replaced a tab with a space
in the blog post where `allocate()` was created.
> Fix for #220: BumpAllocator overflow

- Cargo.toml
- blog/post/04-printing-to-screen.md
- src/lib.rs
- src/vga_buffer.rs
This PR wraps the `ScreenChar`s in a `Volatile` wrapper in the `Buffer` definition. The `Volatile` wrapper ensures that all accesses are volatile so that the compile can't optimize the writes away. This makes the code a bit more verbose since we can no longer copy whole rows at once.
This PR also updates and restructures the corresponding blog post:
- There is now a new, quite large subsection about volatiles (only a first draft, probably needs some fine-tuning).
- The “Printing to Screen” section was split into “Printing Characters” and “Printing Strings”. 
- We now derive Debug, Clone, and Copy for more types after fixing the first _“cannot move out of borrowed content”_ error. Otherwise we would get an error when defining the character array in the Buffer type. This change avoids a …
> Printing to Screen: Use volatile operations for accessing the VGA Buffer

- blog/post/02-entering-longmode.md
- blog/post/03-set-up-rust.md
- blog/post/05-allocating-frames.md
- blog/post/07-remap-the-kernel.md
- blog/post/09-catching-exceptions.md
Most of these updates are quite old and thus distracting. Instead, we now have a “Recent Changes” box in the sidebar of the front page.
> Remove old “Update” sections

- blog/post/06-page-tables.md
We have to map the P4 table recursively before setting paging - can't do this wherever we'd like.
> map the P4 table recursively before setting paging

- blog/post/07-remap-the-kernel.md
A link to the source code of the `tlb::flush_all` function was broken.
> Fixed broken link in 07-remap-the-kernel.md

- blog/post/10-better-exception-messages.md
- blog/post/11-returning-from-exceptions.md
- src/interrupts/mod.rs
This PR changes the type of exception handler functions. Instead of a `*const ExceptionStackFrame`, they now take a `&ExceptionStackFrame` as argument. The reason is that they require the pointer to be valid (they used to blindly derefence the raw pointer). So the old implementation was unsound, since the functions used to violate memory safety when an invalid pointer is passed.
A consequence of this change is that we should no longer modify the exception stack frame (since we have an immutable reference to it). And transmuting a `&` to a `&mut` is undefined behavior. So the last section of _Returning from Exceptions_ (_“Page Faults as Breakpoints”_) becomes even more hacky. Therefore, this PR removes that section. Instead, we now test the iretq logic by entering an endless loop between …
> Exceptions: Take the ExceptionStackFrame per reference

- blog/post/06-page-tables.md
Gil left [this comment](http://os.phil-opp.com/modifying-page-tables.html#comment-3015227025) regarding #246 on the blog:
> You said that the P4 recursive loop must be set before paging is enabled.
But I wonder - the memory is currently identity mapped, so what difference is there in P4_table address in with/without paging?
I think this is correct. I also tested it and it still works when I do the recursive mapping after enabling paging.
Reverts phil-opp/blog_os#246
> Revert "map the P4 table recursively before setting paging"

- Xargo.toml
- blog/post/11-returning-from-exceptions.md
Xargo 0.3.0 was just released: https://users.rust-lang.org/t/xargo-v0-3-0-released-build-your-own-std/8571
By default it compiles only `core` now. However, we also need `alloc` and `collections`. We can enable them by creating a file named `Xargo.toml` with the following content:
```toml
[target.x86_64-blog_os.dependencies]
collections = {}
```
Fixes #271
> Add a Xargo.toml for xargo 0.3.0 and update the corresponding post

- blog/post/02-entering-longmode.md
- src/arch/x86_64/boot.asm
- src/arch/x86_64/long_mode_init.asm
The Intel and AMD manuals state that no data segment is needed in 64-bit mode. However, the `iretq` instruction expects a valid data segment selector or a null selector in the `ss` register.
This PR removes all ignored fields from the GDT structure overview in _Entering Long Mode_. It also removes the data segment from the assembly 64-bit GDT and no longer reloads the data segment registers before jumping to 64-bit mode. Instead, we reload them with null selectors after we're in 64-bit mode.
Fixes #273
Fixes #277
> Remove the data segment from assembly 64-bit GDT

- src/arch/x86_64/boot.asm
Since we started using the IDT struct specified on the x86_64 crate, we
need more space for all the 256 entries and not only for the first 16
(or 32?) entries as on the old IDT type.
- This fix #294
- This change must be included on the new planned blog post #292
> Expand stack to 16k

- Cargo.toml
- blog/content/post/06-page-tables.md
This PR:
- removes the testing of the `translate` method since the stack overflow no longer occurs (as we're using a 16KiB stack now)
- removes an unneeded unsafe block
- updates the x86_64 crate to version 0.1.2, which provides the `int3` function that we need in “Handling Exceptions” (this was reported in #303)
> Bring “Page Tables” post up to date again

- blog/content/post/08-kernel-heap.md
> Kernel Heap: Mention Xargo.toml and add missing unsafe in code example

- README.md
- blog/content/post/04-printing-to-screen.md
- blog/content/post/05-allocating-frames.md
- blog/content/post/06-page-tables.md
- blog/content/post/07-remap-the-kernel.md
- blog/content/post/08-kernel-heap.md
- blog/content/post/09-handling-exceptions.md
- blog/content/post/10-double-faults.md
I followed the posts step-by-step from the very beginning again and fixed various things along the way (#311, #317, #318, #319). The resulting code can be found in the `post_1`, `post_2`, etc. tags. Instead of branching off the master branch, these new tags are completely unrelated to any other branch (i.e. they form a completely separate history).
This makes our backporting process much easier. With the previous system, we needed to cherry-pick a fix to all affected tags (and resolve the merge conflicts). Now we can just cherry-pick the fix once and rebase all following tags on their predecessor (e.g. `post_3` on `post_2`, `post_4` on `post_3`, and so on). The new `post_X` names make it easy to automate this rebasing process (rebase `post_N` on `post_{N-1}`).
This PR also fixes #303.
I …
> Link to new `post_X` tags

- blog/content/post/04-printing-to-screen.md
- blog/content/post/06-page-tables.md
- src/memory/paging/mapper.rs
- src/vga_buffer.rs
> Unique::get/get_mut were renamed to as_ref/as_mut

- Xargo.toml
- blog/content/extra/cross-compile-libcore.md
- blog/content/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/posts/08-kernel-heap/index.md
- src/lib.rs
Fixes #332 
See rust-lang/rust#42648
> The collections crate was merged into the alloc crate

- blog/content/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/posts/03-set-up-rust/index.md
- x86_64-blog_os.json
There is a new required field for target configuration files: `target-c-int-width`. This field controls the size of the `argc` parameter and the return type of the native main function in `std` applications. (For `no_std` applications/libraries, we don't really need this field.) We set the value to 32, since it's the size of an `int` in most C calling conventions (including the 64-bit Linux calling convention).
See rust-lang/rust#44906 for more details.
Fixes #353
> Add new required target-c-int-width field to target json

- blog/content/posts/04-printing-to-screen/index.md
- src/lib.rs
The `const_fn` feature gates were individualized in https://github.com/rust-lang/rust/pull/43017 to allow stabilizing _uses_ of const fn without stabilizing const fn declarations.
> Add new `const_unique_new` feature gate

- libs/bump_allocator/src/lib.rs
- libs/hole_list_allocator/src/lib.rs
- src/lib.rs
- src/memory/mod.rs
This version follows the new interface. I've tried to make the transition to the existing version of the hole_list_allocator easier so I've kept that pattern of having a init() function etc. 
If this version of the bump allocator is ok I could do a rewrite of the instructions in the blog.
> A rewrite of the bump allocator to conform to the new API.

- src/lib.rs
This can be fixed by telling the compiler not to mangle the function. Maybe something was changed so that you have to explicitly state to the compiler not the optimise the function away? I don't know. Point is, this builds for me now, whereas before cloning the repo fresh would throw up link errors.
> Fix ld error: Undefined symbol eh_personality.

- blog/content/posts/10-double-faults/index.md
The example code won't compile without a semicolon after the call to `set_handler_fn`.
Sorry for the lazy branch name, did this from the github UI.
> Add missing semicolon in double-fault post

- src/memory/paging/table.rs
Fix an issue where the left shift of the old table address would overwrite the sign extension, making the
address non-canonical and leading to #GPs. This calculates the correct sign extension for the new table
address.
> [Fix #362] Fix sign extension bug in `next_table_address`

- src/lib.rs
The `LockedHeap.init()` function takes `heap_bottom` and `heap_size` as arguments.  Instead, we pass `heap_bottom` and `heap_top`.
This led to unexpected page faults and other weird behavior because the hole sizes were incorrect.
> Use proper size for heap init

- .travis.yml
This is a temporary CI workaround so that Travis passes until #379 is resolved
> Fix travis with workaround for xargo issue

- .travis.yml
- Makefile
This PR resolves #379 by manually setting `RUST_TARGET_PATH` to `pwd` in the makefile.
[Some background can be found in this comment:](https://github.com/japaric/xargo/issues/186#issuecomment-354503358)
>Due to rust-lang/cargo#4788 now all users of custom targets will have to set RUST_TARGET_PATH to the directory that contains the specification file if they have any dependency declared in Cargo.toml.
There hasn't been any activity regarding the breakage caused by rust-lang/cargo#4788, so let's change the Makefile so that users don't have to manually set the nightly version anymore.
> Allow users to use latest nightly compiler without manually setting environment variable

- blog/content/posts/03-set-up-rust/index.md
Fix issue with undefined reference to `rust_eh_personality' when compiling in blog post
> Fix eh_personality reference error

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
Some nitpick corrections for #360.
I am not sure if I understood the following sentence correctly: `- The standard is written for the C programming language. That means lots of C-typical structures are present, such as linked lists in the [boot information].`
In its original form it was not really clear what is meant here. I tried to guess and correct in that way, but briefly glancing over the linked boot information, I was not able to spot linked lists :confused:
> Nitpicks for second article

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- x86_64-blog_os.json
Corrected typo in second edition blog post.
Closes #391.
> Update `"panic"` to `"panic-strategy"`

- blog/content/posts/03-set-up-rust/index.md
Not entirely necessary, but I moved the project directory around a couple of times, which broke the override I set with `rustup override`. The `rust-toolchain` file can be used to keep you from having to set the override again when the directory is moved. Using a `rust-toolchain` file works since rustup 1.5.0.
References:
* [rustup changelog](https://github.com/rust-lang-nursery/rustup.rs/blob/master/CHANGELOG.md#150)
* [rustup PR adding rust-toolchain file functionality](https://github.com/rust-lang-nursery/rustup.rs/pull/1172)
> Add information on rust-toolchain file to post 3

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
I'm fairly sure that the idea trying to be put across here is that old bootloaders can still use the code. I'm fairly sure this should be "archaic" in that case, not "arcane".
> Switch (possible) typo, arcane --> archaic

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
There is an extra word in "the entry point is _the_ called `main`".
It's possible that "the entry point is _then_ called `main`" was intended,
but it works without the word just as well, so just remove it.
> Remove extra "the"

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
@phil-opp might want to consider putting the `-Z pre-linker` flags in cargo.toml instead of passing it in manually
> Added more specific instructions for nightly

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- src/vga_buffer.rs
Avoids confusion by using different names for the two methods (and keeping them both) instead of naming both `write_str` as before.
> Separate Writer::write_string and fmt::Write::write_str methods

- .appveyor.yml
- .travis.yml
- Cargo.toml
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
We just released a new version of the bootimage tool in https://github.com/rust-osdev/bootimage/pull/6. Instead of just `bootimage` the tool now expects subcommands, so we need to invoke it like `bootimage build`. The tool is now configurable through a Cargo.toml entry. For the blog we will use a default target so that we can omit the `--target` parameter.
> Update for bootimage 0.2.0

- Cargo.toml
- Xargo.toml
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- src/main.rs
Since https://github.com/rust-lang/rust/pull/49503, Rust automatically injects a dependency on `compiler_builtins` whenever a dependency on `core` is injected (i.e. all `no_std` applications that aren't `no_core`). This means that compilation fails if xargo builds only `core` (which is the default).
To also build `compiler_builtins`, a `Xargo.toml` with the following content is required:
```toml
[dependencies.core]
stage = 0
[dependencies.compiler_builtins]
features = ["mem"]
stage = 1
```
The `features = ["mem"]` line is not required, but removes the need for `rlibc`.
> Rust automatically injects a dependency on `compiler_builtins` now

- .appveyor.yml
- .travis.yml
- Cargo.toml
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
Since https://github.com/rust-lang/rust/pull/49019 Rust supports passing paths as `--target` (with `.json` extension). With https://github.com/rust-lang/cargo/pull/5228, Cargo automatically converts these paths to absolute paths, so that the `RUST_TARGET_PATH` environment variable is no longer neccessary.
The only missing piece was [xargo](https://github.com/japaric/xargo), but unfortunatly the PR at https://github.com/japaric/xargo/pull/205 got no attention. Since there are other unaddressed issues (e.g. https://github.com/japaric/xargo/issues/214) and xargo is in maintainance mode, we decided to create [cargo-xbuild](https://github.com/rust-osdev/cargo-xbuild) as a simplified fork of xargo to fix these issues.
This PR updates the second edition to use `cargo xbuild` instead of `xargo` …
> No more RUST_TARGET_PATH

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
"as *const u8" seems to be not needed
> remove redundant code in _start

- blog/content/first-edition/posts/04-printing-to-screen/index.md
- blog/content/first-edition/posts/09-handling-exceptions/index.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/06-cpu-exceptions/index.md
For #445 
These were the only links I found that pointed to the "There is a new edition of the book and this is an old link." page.
With this merged, I'd consider #445 fixed
> Fix links that pointed to a redirection page

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
The feature flag for `abi_x86_interrupt` needs to be in `main.rs`.
Putting the feature flag in my lib.rs did not resolve the error. I assume this was an oversight when updating this chapter from the first edition, because the error message in the blog also refers to a separate module `interrupts.rs` that was never mentioned in this edition.
> Fix: should be `main.rs` instead of `lib.rs`

- blog/content/second-edition/posts/05-integration-tests/index.md
Just a typo patch -- there was a missing semicolon after the module declaration in the example code.
Edit: It appears the travis build is failing for unrelated reasons.
> Add missing semicolon in integration tests post

- Cargo.lock
- Cargo.toml
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/05-integration-tests/index.md
- src/lib.rs
- src/main.rs
See https://github.com/rust-osdev/bootimage/pull/16 and https://github.com/rust-osdev/bootloader/pull/20.
> Update to bootimage 0.5.0

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
Writer.write_str does not return Result so it should be error if we call unwrap()
> [second edition: 03 vga text buffer] Fix example code

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/04-unit-testing/index.md
- blog/content/second-edition/posts/05-integration-tests/index.md
- src/bin/test-basic-boot.rs
- src/bin/test-exception-breakpoint.rs
- src/bin/test-exception-double-fault-stack-overflow.rs
- src/bin/test-panic.rs
- src/main.rs
#465 
I haven't tried compiling or running this. I'm new to this, and the changes seem trivial.
I did a grep search of  "panic_implementation" and made the changes. Mine now only comes up with 3 hits from `grep -r "panic_implementation"` which is a discusion on RFC 2070 and changes to `panic_handler`
Thank you for putting this blog together!
> Rfc 2070 panic implementation deprecated

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
- blog/content/second-edition/posts/07-double-faults/index.md
- src/bin/test-exception-breakpoint.rs
- src/bin/test-exception-double-fault-stack-overflow.rs
- src/interrupts.rs
- src/lib.rs
- src/main.rs
As discussed in #473 and https://github.com/acheronfail/blog_os/pull/1/files.
This PR re-writes the 6th and 7th posts so that all exception related code lives in `src/interrupts.rs`.
> Refactor exception code into new `interrupts` module

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- src/vga_buffer.rs
This PR addresses [this comment](https://github.com/phil-opp/blog_os/issues/405#issuecomment-431896303). It turns out that I had made a mistake, and the original code uses `...` instead of `..`. It's unclear which syntax out of `...` and `..=` will become standard in future, so we can leave it for now.
Thanks again.
> Minor code adjustments.

- Cargo.toml
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
When trying to build `spin` 0.4.6 on current nightly, I get the following error:
```
error[E0635]: unknown feature `const_atomic_usize_new`
--> /home/donald/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs:8:76
|
8 | #![cfg_attr(feature = "const_fn", feature(const_fn, const_unsafe_cell_new, const_atomic_usize_new))]
|                                                                            ^^^^^^^^^^^^^^^^^^^^^^
error[E0635]: unknown feature `const_unsafe_cell_new`
--> /home/donald/.cargo/registry/src/github.com-1ecc6299db9ec823/spin-0.4.8/src/lib.rs:8:53
|
8 | #![cfg_attr(feature = "const_fn", feature(const_fn, const_unsafe_cell_new, const_atomic_usize_new))]
|      
```
This change resolves this, though I haven't tested it for other problems.
> Bump spin version as 0.4.6 can't build on nightly

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
Fix a small typo in cpu-exceptions blog post.
> Fix typo in CPU exceptions post

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
I noticed a minor typo while following along with the blog on the CPU Exceptions page.
> Fix minor typo on cpu-exceptions page

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
I noticed that the link for the System V ABI was broken, and it was just due to a "-" instead of an "_". This pr should fix that.
I also want to say thanks so much for this project! It's incredibly inspiring.
> Fix minor url typo for System V ABI on cpu-exceptions page

- Cargo.lock
- Cargo.toml
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/05-integration-tests/index.md
- src/lib.rs
It is now also linked with LLD, so it can be compiled out of the box on Linux, Windows, and macOS.
This means that we no longer need the `bootloader_precompiled` crate.
> The bootloader is now buildable on all platforms

- Cargo.toml
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/04-unit-testing/index.md
- blog/content/second-edition/posts/05-integration-tests/index.md
- blog/content/second-edition/posts/06-cpu-exceptions/index.md
- blog/content/second-edition/posts/08-hardware-interrupts/index.md
- src/bin/test-basic-boot.rs
- src/bin/test-exception-breakpoint.rs
- src/bin/test-exception-double-fault-stack-overflow.rs
- src/bin/test-panic.rs
- src/interrupts.rs
- src/lib.rs
- src/main.rs
- src/serial.rs
- src/vga_buffer.rs
This updates the blog to use the upcoming [2018 edition](https://rust-lang-nursery.github.io/edition-guide/rust-2018/index.html) of Rust, which is currently in beta and already the default on nightly. It changes a few local import paths (now with a `crate::` prefix) and removes all `extern crate` definitions and `macro_use` attributes.
This PR changes a lot of code across all posts, so there might be some things in the posts that I forgot to update. Please let me know if you see anything! [Preview of the changes](https://rust-2018--blog-os.netlify.com/)
Fixes #499 
Fixes #500
> Update to the 2018 edition of Rust

- blog/content/second-edition/posts/06-cpu-exceptions/index.md
- src/bin/test-exception-breakpoint.rs
The current test only tests the x86_64 crate, not any property of our kernel. This was reported in https://github.com/phil-opp/blog_os/issues/450#issuecomment-455771614.
> Rewrite breakpoint test

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
seems rustc-guide already move to https://rust-lang.github.io/rustc-guide/
> fix unreachable link

- blog/content/second-edition/posts/10-advanced-paging/index.md
This function casts a usize argument to a pointer, and dereferences it.
This is undefined behavior unless level_4_table_addr is the address of a
valid PageTable, so the function should be marked 'unsafe'
> Make translate_addr unsafe

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
There are several links to older versions of the rust book that have no content. I updated the links that were one-for-one replacements to the new rust book URL. 
There are also some links to language reference pages that I think might be more appropriate to link to pages with more narrative. I started to make some of those changes (line 499 refcell), but thought I should ask before making anything beyond broken-link changes.
> fix broken links in VGA buffer post

- .travis.yml
- README.md
- azure-pipelines.yml
- rust-toolchain
adding linker args can be done with the stable `-Clink-arg`.
the difference with `-Zpre-link-arg` is that the args are appended instead of prepended. is that distinction important in this case?
> don't require nightly compiler from freestanding binary

- src/interrupts.rs
I have changed the source code but I don't know how to reflect the changes on the blog.
This is the first time I contribute to something, I don't really know what I'm doing exactly.
I hope it does not only works for me, it would be nice if someone could clone my modifications locally to be sure it's actually working.
The first commit (9f6ea55) is the most important and the changes are precisely detailed in the commit description.
> encapsulate the hardware interrupts' indexes + minor corrections

- blog/content/first-edition/posts/10-double-faults/index.md
- blog/content/second-edition/posts/07-double-faults/index.md
> double-faults misspell fixed

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/10-paging-implementation/index.md
The `post-*` tags were already updated.
This update only changes how the bootloader crate is build behind the scenes and should not require user-facing changes. See the changelogs of [`bootloader`](https://github.com/rust-osdev/bootloader/blob/master/Changelog.md) and [`bootimage`](https://github.com/rust-osdev/bootimage/blob/master/Changelog.md) for more information.
> Update to new bootloader 0.5.1 and bootimage 0.7.2

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
This pull request rewrites the section about overwriting the entry point. Instead of recommending to pass platform-specific arguments to the linker, the post now solves the linker errors by compiling for the bare metal `thumbv7em-none-eabihf` target. This makes much more sense, since it is the same approach that we use in the second post (by using a custom bare metal target).
We keep the old section about the platform specific linker arguments, but perform the following changes:
- The section is now optional and hidden by default. It was de facto optional before since the second post does not use the linker arguments at all. It's main motivation – getting a working `cargo build` at the end of the post – is now achieved by building for `thumbv7em-none-eabihf`, so we no longer need it for …
> Rewrite the linking section of "A Freestanding Rust Binary"

- azure-pipelines.yml
See https://github.com/phil-opp/blog_os/pull/577 for information about the rewrite.
This commit updates the azure pipelines CI script in the following way:
- build on all three OSs
- build for thumbv7em-none-eabihf
> Update CI build for rewrite of "A Freestanding Rust Binary"

- .appveyor.yml
- .cargo/config
- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- azure-pipelines.yml
This updates the `post-02` branch for the changes of #582:
- Adds a `.cargo/config` file that defines a default target and a target runner
- Updates the CI scripts
- Updates the Readme with new build and run instructions
- Updates the bootloader to version 0.6.0 ([changelog](https://github.com/rust-osdev/bootloader/blob/master/Changelog.md#060))
- This is required for the updated Paging Implementation post
Blocked on #582.
> Add `.cargo/config` file to post-02 branch and update bootimage

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/06-cpu-exceptions/index.md
- blog/content/second-edition/posts/08-hardware-interrupts/index.md
This PR updates the "Minimal Rust Kernel" post. It sets up a `.cargo/config` file to specify a default target and a runner for targets with `os=none`. This makes it possible to launch the kernel in QEMU through a simple `cargo xrun`.
The goal is that the user can use the familiar cargo commands and never needs to invoke `bootimage` directly. We still need `cargo-xbuild` to build the sysroot, so the user has to prefix every cargo command with an `x` for now, but cargo will hopefully integrate this functionality soon.
The only place where the user has to use a non-standard cargo command, is when they want to create a bootable disk image for booting from an USB stick. For this case, the bootimage crate supports a `cargo bootimage` subcommand, which is equivalent to `bootimage build` but …
> Minimal Rust Kernel: Use a runner to make cargo xrun work

- src/main.rs
- src/memory.rs
The use of `impl trait` as return value made it very hard to put the BootInfoFrameAllocator in a static, e.g. for accessing it from a page fault handler. See https://github.com/phil-opp/blog_os/issues/593 for more information.
This PR makes `BootInfoFrameAllocator` non-generic. It now has a `MemoryMap` field and `usable_frames` method for creating the frame iterator. In an additional field, it keeps track of the last returned frame so that no frame is returned twice.
This _might_ have a bit worse performance because we recreate the iterator on every allocation, but I don't think that this is a problem for the blog for now (also, it doesn't make much sense to optimize for performance without any benchmarks).
Post update in https://github.com/phil-opp/blog_os/pull/596.
> Avoid generic impl trait parameters in BootInfoFrameAllocator

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
[Changelog of `x86_64` 0.6.0](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#060):
* **Breaking**: Make the FrameAllocator unsafe to implement. This way, we can force the implementer to guarantee that all frame allocators are valid. See [rust-osdev/x86_64#69](https://github.com/rust-osdev/x86_64/issues/69) for more information.
In addition we make the `BootInfoFrameAllocator::init` method unsafe, because the caller must guarantee that the usable frames of the memory map were not used somewhere else.
Code update in https://github.com/phil-opp/blog_os/pull/599.
> Update to version 0.6.0 of x86_64

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/memory.rs
[Changelog of `x86_64` 0.6.0](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#060):
- **Breaking**: Make the FrameAllocator unsafe to implement. This way, we can force the implementer to guarantee that all frame allocators are valid. See rust-osdev/x86_64#69 for more information.
> Update `post-09` branch for version 0.6.0 of `x86_64` crate

- Cargo.lock
- Cargo.toml
[Changelog](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#070):
- **Breaking**: `Port::read` and `PortReadOnly::read` now take `&mut self` instead of `&self` ([#76](https://github.com/rust-osdev/x86_64/pull/76)).
Post update in https://github.com/phil-opp/blog_os/pull/607
> Update x86_64 to version 0.7.0

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
Code update in https://github.com/phil-opp/blog_os/pull/606
> Update posts for x86_64 version 0.7.0

- blog/content/second-edition/posts/04-testing/index.md
Updates the testing post for the changes introduced in #604.
> Update testing post to use `-serial stdio` instead of `-serial mon:stdio`

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/static/css/main.css
Almost all the code in the blog uses spaces instead of tabs.
This change fixes 3 places where there was inconsistancy.
This was causing some of the content to appear misaligned.
Now tabs are only used in:
- Makefiles
- Dockerfiles
- Command output (from `objdump` and `diff`) containing tabs
- `.fish` files
> Always use spaces for code (if possible)

- blog/content/second-edition/posts/04-testing/index.md
Instead of checking just a single string component like before.
Fixes the issues reported in https://github.com/phil-opp/blog_os/issues/591#issuecomment-494615540. Alternative to https://github.com/phil-opp/blog_os/pull/610.
cc @xj42
> Rewrite CompareMessage to check the whole string

- azure-pipelines.yml
- blog/content/first-edition/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/first-edition/posts/02-entering-longmode/index.md
- blog/content/first-edition/posts/03-set-up-rust/index.md
- blog/content/first-edition/posts/07-remap-the-kernel/index.md
- blog/content/first-edition/posts/08-kernel-heap/index.md
- blog/content/first-edition/posts/09-handling-exceptions/index.md
- blog/content/second-edition/extra/disable-simd/index.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/deprecated/05-integration-tests/index.md
This PR fixes some typos on the blog and adds a typo check to the CI job.
@alex-bender Thanks for suggesting misspell!
> Use misspell tool to look for common typos

- .travis.yml
According to https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos, travis does not run `brew update` by default. The problem is that without it, the installation of QEMU fails with:
```
Error: Your Homebrew is outdated. Please run `brew update`.
Error: Kernel.exit
```
This PR fixes the CI failure by running `brew update` before installation, even though it needs more time.
> Run `brew update` on macOS to fix travis CI failure

- blog/content/status-update/2019-06-04.md
This PR adds an "Updates in June 2019" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Add June status update post

- blog/content/second-edition/posts/04-testing/index.md
This pull request replaces the previous panic handler test, which didn't really test any property of our kernel, with a general `should_panic` test. This simplifies things, for example there is no more panic line constant or special struct for comparing the panic message.
Issue reported in https://github.com/phil-opp/blog_os/issues/591#issuecomment-518351816.
Code update in https://github.com/phil-opp/blog_os/pull/651.
> Rewrite section about no-harness tests

- blog/content/second-edition/posts/05-cpu-exceptions/index.md
Thanks for the great tutorial. Here is a typo I found.
> Fix typo in 05-cpu-exceptions

- blog/content/second-edition/posts/06-double-faults/index.md
Thanks for the amazing work.
Removed an extra "because".
> fix typo in 06-double-fault

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
The breaking change compared to the previously used version 0.6.4 is that now at least bootimage version 0.7.7 is required. See the [bootloader changelog](https://github.com/rust-osdev/bootloader/blob/master/Changelog.md#080) for details.
With this update, the compile time of the project is now drastically reduced. The reason is that the new bootloader version no longer compiles its dependencies when its only used as library.
> Update to bootloader 0.8.0

- .github/workflows/build-site.yml
The external link checker of the `zola check` command has false positives, e.g. https://github.com/getzola/zola/issues/805.
> Don't fail job if `zola check` fails

- blog/templates/404.html
- blog/templates/first-edition/base.html
- blog/templates/first-edition/handling-exceptions-with-naked-fns.html
- blog/templates/first-edition/index.html
- blog/templates/first-edition/page.html
- blog/templates/redirect-to-frontpage.html
- blog/templates/second-edition/base.html
- blog/templates/second-edition/index.html
- blog/templates/second-edition/page.html
Zola 0.9 changed the way the `safe` filter is automatically applied and thus lead to escaping issues. This pull request fixes this by adding the `safe` filter in more places in the templates.
Fixes the escaping issues reported in https://www.reddit.com/r/rust/comments/de5hvu/writing_an_os_in_rust_updates_in_september_2019/f2xzr3o/.
> Fix escaping issues by adding `safe` filters in more places

- src/interrupts.rs
This avoids an endless loop when a double fault occurs while running `cargo xtest`.
The blog post already uses the panic version, it is just the `post-06` branch that is out of sync.
Reported in https://github.com/phil-opp/blog_os/issues/449#issuecomment-551581648.
> Use panic! instead of println! + loop in double fault handler

- blog/content/second-edition/posts/07-hardware-interrupts/index.md
See https://github.com/phil-opp/blog_os/pull/687 and https://github.com/phil-opp/blog_os/pull/689.
> Hardware Interrupts: Don't replace panic in double fault handler

- src/interrupts.rs
See https://github.com/phil-opp/blog_os/pull/687
Requires an update to the _Hardware Interrupts_ post (_Edit_: Done in https://github.com/phil-opp/blog_os/pull/690).
> post-07: Use panic instead of println + hlt_loop for double fault handler

- src/interrupts.rs
- tests/stack_overflow.rs
Required by x86_64 0.8.0.
Update to x86_64 0.8.0 ocurred in https://github.com/phil-opp/blog_os/pull/701.
> Make double fault handlers diverging

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
- blog/content/second-edition/posts/10-heap-allocation/index.md
[Changelog of `x86_64`](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#080)
The corresponding updates to the `post-XX` branches were already merged in #701, #702, and #703.
> Update blog to x86_64 version 0.8.1

- LICENSE-MIT
- README.md
- blog/config.toml
- blog/content/LICENSE-CC-BY-NC
- blog/content/README.md
This licenses the blog content under the [Creative Commons Attribution-NonCommercial 4.0 International](https://creativecommons.org/licenses/by-nc/4.0/) license. The main motivation for this is to clarify the copyright situtation for third-party contributions, such as translations (see #692).
Note that the license does not permit any commercial use.
> License the `blog/content` folder under CC BY-NC

- blog/static/css/main.css
- blog/templates/macros.html
instead of only providing a 'Community Translation' link.
~Blocked on https://github.com/getzola/zola/issues/859.~ The required functionality was merged in https://github.com/getzola/zola/pull/863.
> Show translated content directly on index page

- src/allocator.rs
- src/lib.rs
The Rust issue that the #[global_allocator] cannot be defined in submodules was fixed.
> Move #[global_allocator] into allocator module

- blog/content/second-edition/posts/10-heap-allocation/index.md
Reported in https://github.com/phil-opp/blog_os/issues/627#issuecomment-554616566
Code update in https://github.com/phil-opp/blog_os/pull/714.
> It is now possible to define allocators in submodules

- tests/heap_allocation.rs
Instead of using a hardcoded number of boxes, use the HEAP_SIZE constant. This ensures that we get a test failure because of an out-of-memory error when the allocator does not reuse freed memory.
> Update many_boxes test to scale with heap size

- src/allocator/bump.rs
- src/allocator/linked_list.rs
This prevents integer overflow on large allocations.
Suggested in https://github.com/phil-opp/blog_os/issues/720#issuecomment-578556562.
Post update in https://github.com/phil-opp/blog_os/pull/727.
> Use checked addition for allocator implementations

- blog/content/second-edition/posts/10-heap-allocation/index.md
We forgot to remove the `allocator::` prefix when moving the ALLOCATOR declaration into the `allocator` module in #714.
Reported in https://github.com/phil-opp/blog_os/issues/627#issuecomment-579286343.
> Fix dummy allocator code example

- blog/content/status-update/2020-02-01.md
- blog/templates/status-update-page.html
This PR adds an "Updates in January 2020" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in January 2020

- blog/content/second-edition/posts/11-allocator-designs/index.md
These extensions make it possible to reuse freed memory in more cases. While they would fix the failing test, they are no general solutions.
Suggested by https://github.com/phil-opp/blog_os/issues/720#issuecomment-576405011.
> Mention potential bump allocator extensions

- src/allocator/bump.rs
- src/allocator/linked_list.rs
Suggested in https://news.ycombinator.com/item?id=22230966
> Don't panic on overflow in allocator; return null pointer instead

- blog/content/second-edition/posts/11-allocator-designs/index.md
Update post for changes introduced in #738
> Update Allocator Designs post to signal OOM instead of panicking on overflow

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.zh-CN.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.zh-TW.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.zh-CN.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.zh-CN.md
- blog/content/second-edition/posts/04-testing/index.zh-CN.md
- blog/static/css/main.css
- blog/templates/second-edition/page.html
List the usernames of translators on translated posts to properly attribute the translation.
cc @luojia65 @Rustin-Liu @TheBegining @wusyong: This lists your usernames on posts that you translated. Let me know if you have a problem with this.
> Add metadata to translations and list translators

- .github/workflows/build-site.yml
- blog/config.toml
- blog/content/first-edition/extra/naked-exceptions/01-catching-exceptions/index.md
- blog/content/first-edition/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/first-edition/extra/set-up-gdb/index.md
- blog/content/first-edition/posts/03-set-up-rust/index.md
- blog/content/first-edition/posts/04-printing-to-screen/index.md
- blog/content/first-edition/posts/05-allocating-frames/index.md
- blog/content/first-edition/posts/06-page-tables/index.md
- blog/content/first-edition/posts/07-remap-the-kernel/index.md
- blog/content/first-edition/posts/08-kernel-heap/index.md
- blog/content/first-edition/posts/09-handling-exceptions/index.md
- blog/content/first-edition/posts/10-double-faults/index.md
- blog/content/news/2018-03-09-pure-rust.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.zh-CN.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.zh-TW.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/_index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.zh-CN.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.zh-CN.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/11-allocator-designs/index.md
- blog/content/second-edition/posts/deprecated/04-unit-testing/index.md
- blog/content/second-edition/posts/deprecated/05-integration-tests/index.md
This pull request enables the dead link checks using the `zola check` command. It fixes all found dead links and dead anchors, which were quite a lot.
> Use zola check to check for dead links; fix all dead links found

- blog/static/css/main.css
- blog/static/js/main.js
- blog/templates/second-edition/index.html
- blog/templates/second-edition/page.html
This displays a language selector if there are translations for the current page. The selector is only shown for content languages that the user enabled in their browser.
The selector is very rudimentary at the moment and only displays the language code. For the future, I would like to replace it with the proper name, e.g. Chinese (Simplified) instead of `zh-CN`.
> Add a language selector for browser-supported languages

- Cargo.lock
- Cargo.toml
- src/interrupts.rs
I recently updated this in my project so I figured I'd help out since you do such great work. This should fix #742. The `keyboard::new` now takes 3 arguments, with the third being `pc_keyboard::HandleControl`. The two options are:
```
MapLettersToUnicode
If either Ctrl key is held down, convert the letters A through Z into Unicode chars U+0001 through U+001A. If the Ctrl keys are not held down, letters go through normally.
Ignore
Don't do anything special - send through the Ctrl key up/down events, and leave the letters as letters.
```
I left it `MapLettersToUnicode` for now since there's a match to handle Unicode characters, but it can be changed to `Ignore` if you prefer, just let me know.
> Updated pc-keyboard to `0.5.0`

- blog/content/second-edition/posts/06-double-faults/index.md
Removed the word "executes" from "The CPU executes tries to write to `0xdeadbeef`, which causes a page fault."
> Removed unnecessary word

- blog/content/second-edition/posts/09-paging-implementation/index.md
> Use `a` instead of `an` before a consonant

- blog/content/second-edition/posts/12-async-await/index.md
`WaitingOnFooTxt` -> `WaitingOnBarTxt`
> Fixed minor typo in example code

- blog/content/second-edition/posts/12-async-await/index.md
Fix typo: `s/sately/safely/`.
_(thank you for your amazing work)_
> Fix typo: "s/sately/safely/"

- src/task/executor.rs
- src/task/mod.rs
Deriving the task ID from the heap address of the future does not work for zero-sized futures because they are not backed by a real allocation.
Reported in https://github.com/phil-opp/blog_os/issues/768#issuecomment-606375263.
> Use a static counter for assigning task IDs

- blog/content/second-edition/posts/12-async-await/index.md
Thanks for the great article! Here are three small language corrections.
> Fix 3 typos in Async/Await

- blog/content/second-edition/posts/12-async-await/index.md
This note is no longer needed since 2020-04-06 (see https://rust-lang.github.io/rustup-components-history/).
> Remove note about rustfmt and clippy components

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
This line confused me. I thought I'd read past something but it looks like the content in post-01 that it is referring to changed in 0b9ca847356c3f932e038d3b32d5e85a6e53e971.
Thanks for the blog!
> We no longer make entry points for Windows and macOS in post-01

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
The [current version](https://os.phil-opp.com/minimal-rust-kernel/#printing-to-screen) of the book states that `unsafe` allows you to do four additional things.
It seems the list of "unsafe superpowers" has expanded somewhat:
https://doc.rust-lang.org/stable/book/ch19-01-unsafe-rust.html#unsafe-superpowers
Here's the commit which changed the official documentation:
https://github.com/rust-lang/book/commit/5af8895ec347e2ea4d6ec71e3e6680ec3d9c32f5
Thank you so much for you work.
> Add one more unsafe superpower

- src/task/executor.rs
Proposed in https://github.com/phil-opp/blog_os/issues/768#issuecomment-629605586
This pull request also renames the `waiting_tasks` map to `tasks` and makes `run_ready_tasks` operate on `&mut Task` references instead of removing and re-inserting tasks from the map.
As another simplification, we now use the entry API on the `waker_cache` map instead of manual if conditions. Unfortunately this requires to destructure `self` into its fields because [RFC 2229]( https://github.com/rust-lang/rfcs/pull/2229) is not yet implemented (see the [tracking issue](https://github.com/rust-lang/rust/issues/53488)), but I still think that the new approach is simpler.
> Simplify executor by merging task_queue and wake_queue

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
The `post-x` branches were already updated in commit b1bf0873ceb82c8bf88eee914c2993df91a25347.
This is the first step required for fixing #807.
> Update bootloader to v0.9.3

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
- blog/content/second-edition/posts/10-heap-allocation/index.md
- blog/content/second-edition/posts/12-async-await/index.md
There were some breaking changes between versions 0.9.6 and 0.11.0, so we need to update the code of the _Paging Implemenation_ and _Heap Allocation_ posts a bit. 
The `post-x` branches were already updated in commits 2c303102812ec45093a486bb5281fba69f15ffda, 491889a237013af8dee0accff0f034c3e4b09fd8, and 44ab90f92d5bf9a299ddb6bb3e56923943cbf994.
This is the second step in fixing #807.
> Update x86_64 dependency to version 0.11.0

- tests/stack_overflow.rs
This prevents the compiler from transforming the tail recursive function into a loop, which does not lead to a stack overflow. It also avoids the LLVM bug where functions with side-effect-free endless loops are removed. Thus, the test now also works in `--release` mode.
Suggested by @bjorn3 in https://github.com/phil-opp/blog_os/issues/449#issuecomment-640189459.
> Do a volatile read in stack_overflow test to avoid tail recursion 

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/03-vga-text-buffer/index.zh-CN.md
Thanks for the detailed blog posts, I'm really enjoying them. I noticed that this link has moved so I thought I'd update this post to point to the new location. Cheers!
> Update link to const evaluator documentation

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.zh-CN.md
fix error `error: the legacy LLVM-style asm! syntax is no longer supported`
> docs: remove version lock

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
The grammar for MacOS linker arguments was clunky. Fix it to be grammatically correct.
> Fix grammar for freestanding-rust-binary linker arguments.

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
- blog/content/second-edition/posts/10-heap-allocation/index.md
- blog/content/second-edition/posts/12-async-await/index.md
The [`x86_64` crate](https://github.com/rust-osdev/x86_64) recently published a new version. Noticed that these links still point to `0.11.0` when `0.11.1` is now out. Left the `/deprecated` posts unchanged since they point to very out of date versions. And FYI just used this command to replace all of them:
```sh
find . -name "*.md" -exec sed -i '' "s,https://docs.rs/x86_64/0.11.0/,https://docs.rs/x86_64/0.11.1/,g" {} +
```
Also fixed links to the `PhysAddr` and `VirtAddr` structs which now have a `/addr/*Addr` path (in posts `08,09,10`).
Pretty sure the failed `Zola Check` test is unrelated to my changes.
---
And can I just say, love everything you and all contributors have  done for the Rust community by making OS development so much more approachable in Rust :pray: Just started on [my …
> chore: Update x86_64 crate links to latest version

- .cargo/config
- .cargo/config.toml
- .github/workflows/build-code.yml
- Cargo.lock
- Cargo.toml
- src/main.rs
This pull request implements building using cargo's new [`build-std`](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std) instead of using the [`cargo-xbuild`](https://github.com/rust-osdev/cargo-xbuild) crate.
To enable the `build-std` functionality, we set the `unstable.build-std` configuration key in the `.cargo/config.toml` file. This flag was introduced very recently in https://github.com/rust-lang/cargo/pull/8393, so it only works on the latest nightlies. Unfortunately, rustfmt doesn't build on these nightlies yet, so you have to use `rustup update nightly --force` to install them (results in skipping the rustfmt component).
Functionality-wise, the `build-std` feature behaves almost identical to `cargo-xbuild`. The only difference is that it doesn't enable the …
> Migrate post-02 code from cargo-xbuild to `-Zbuild-std`

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
- blog/content/second-edition/posts/10-heap-allocation/index.md
- blog/content/second-edition/posts/11-allocator-designs/index.md
- blog/content/second-edition/posts/12-async-await/index.md
This updates the blog for the changes in https://github.com/phil-opp/blog_os/pull/835. The changes on the blog include:
- Introduce the `build-std` feature of cargo instead of using `cargo-xbuild` crate :tada:
- Replace all instances of `cargo xbuild/xrun/xtest` with the standard `cargo build/run/test` across the second edition posts
- Add a dependency on `rlibc` to provide `memcpy` etc implementations.
- Update bootloader dependency to version 0.9.8
- Update the 'Heap Allocation' post to enable the `alloc` dependency in the `unstable.build-std` list in `cargo/config.toml`.
- Rename `.cargo/config` file to `.cargo/config.toml`
> Update blog to use `build-std` feature instead of cargo-xbuild

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
I'm not sure if this is a change you'd like, because it's technically not broken or anything. However, if you do, there are a couple of other files to change (4).
https://github.com/rust-lang/rustup/commit/33062a1a08eff4cbfd83027c09a69e496243738f
`add` is an alias and the cli help command also only lists `set` and `unset` for me (no add). For that reason I think it's better to use set (less confusing, in line with cli).
> change rustup override add to rustup override set

- blog/config.toml
- blog/content/first-edition/posts/08-kernel-heap/index.md
- blog/content/second-edition/posts/01-freestanding-rust-binary/index.ja.md
- blog/content/second-edition/posts/_index.ja.md
- blog/templates/second-edition/index.html
This is the first step for adding the Japanese translations.
The first post translation is taken from https://github.com/JohnTitor/blog-os-ja/blob/master/src/01-freestanding-rust-binary.md.
> Add (initial) Japanese translation

- .github/workflows/scheduled-builds.yml
This enables nightly builds of the `post-XX` branches again. This way, we are directly notified if our code is broken by new Rust nightly versions.
We used to have these scheduled builds implemented when we used Travis CI and Azure Pipelines for our CI, but Github Actions did not support that initially (see https://github.community/t/scheduled-builds-of-non-default-branch/16306 and https://github.community/t/how-to-trigger-repository-dispatch-event-for-non-default-branch/14470). With the new `workflow_dispatch` event, we can now
> Use workflow dispatch event to trigger scheduled builds of code branches

- .github/workflows/build-site.yml
- blog/config.toml
- blog/templates/rss.xml
This updates the blog to version 0.11.0 of Zola, which is the static site generator we use.
Most changes in Zola 0.11.0 are RSS feed related. This PR renames a few configuration keys to their new name and uses the `feed_filename` config key to keep our RSS file at `/rss.xml` to avoid breakage. Since the new version fixed anchor checking for uppercase HTML tags, we can remove some `zola check` exceptions.
> Update Zola to 0.11.0

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
This makes it slightly easier to find out more about the JSON file that specifies custom targets.
> Add link to custom targets

- Cargo.lock
- Cargo.toml
Fixes build on latest nightly.
Also updates the `uart_16550` dependency.
> Update `x86_64` to v0.12.1

- src/lib.rs
Fixes the build on the latest Rust nightly.﻿
> Use new `const_mut_refs` feature gate

- .github/workflows/build-site.yml
- blog/templates/first-edition/comments.html
- blog/templates/first-edition/index.html
- blog/templates/first-edition/page.html
- blog/templates/macros.html
- blog/templates/news-section.html
- blog/templates/second-edition/index.html
- blog/templates/second-edition/page.html
- blog/templates/status-update-page.html
- blog/templates/status-update-section.html
This updates `zola`, the static site generator that we use, to version 0.12.1.
There is only one breaking change between version 0.11.0 (our current version) and 0.12.1 that affects us: Page paths now have a leading `/`. This means that we have to remove our manual `/`s in templates to avoid double `//` in the generated code.
I'm most excited about the new support for line highlighting in code blocks, which was added in https://github.com/getzola/zola/pull/1131. This should allow us to properly highlight the lines currently marked with a `// new` comment in our code excerpts.
> Update to zola v0.12.1

- blog/content/second-edition/posts/11-allocator-designs/index.md
This should fix our `zola check` CI job again.
> Fix outdated linked_list_allocator links and description

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- src/main.rs
Part of #862
I can also remove the references to `rlibc` from the blog posts if that saves you time
> Remove rlibc and use compiler-builtins-mem feature

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- src/lib.rs
Update `post-04` branch for changes introduced in https://github.com/phil-opp/blog_os/pull/865.
> Update post-04 to use compiler_builtins `mem` feature instead of `rlibc`

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
Minor change, but keep the shorthand struct initialization seen previously at line 201: https://github.com/phil-opp/blog_os/blame/master/blog/content/second-edition/posts/03-vga-text-buffer/index.md#L201
> Use shorthand initialization from earlier code

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
The commented file path was removed in https://github.com/phil-opp/blog_os/pull/866
This matches the other code snippet additions to `.cargo/config.toml` and `Cargo.toml`, and I was personally tripped up by it 😣
> Specify which file to change for Memory-Related Intrinsics

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
Removed message about recent Rust nightlies not containing `rustfmt`.
> Removed message about rustfmt

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
Previously:
"`mem` feature" led to wrong feature
"`memcpy` etc. implementations" had redundant parenthesis that prevented proper rendering
> Fix some links in 02-minimal-rust-kernel

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/04-testing/index.zh-CN.md
This prevents people from having duplicate code and potentially encountering errors. If both copies are kept the compiler may complain `error: cannot find macro `serial_println` in this scope` in `main.rs`
> Emphasize moving code

- blog/content/second-edition/posts/deprecated/05-integration-tests/index.md
Use specified version instead (it'd be great if Zola could ignore some paths on link-checker, I imagine).
> Fix broken QEMU link

- blog/content/second-edition/posts/03-vga-text-buffer/index.ja.md
The title says it all.
@JohnTitor could you review the translation?
> Translate post-03 to Japanese

- blog/content/edition-2/posts/04-testing/index.md
To make more readable, just add filepath to code blocks.
> Add filepath to code block

- blog/content/edition-2/posts/06-double-faults/index.md
2 small fixes 
"we don't have implemented" -> "we haven't implemented"  
and 
"We use lazy_static again, because Rust's const evaluator is not powerful enough yet" -> "As before, we use lazy_static again." 
just to remove what has already been said a few paragraphs up. 
Thank you for this amazing resource!
> Minor grammar fixes

- blog/content/edition-2/posts/09-paging-implementation/index.md
Minor rewrite of the `flap_map` explanation of frame allocator, removing the reference to `into_iter` that is no longer in the code. 
Hope that helps!
> Improve explanation for `BootInfoFrameAllocator::usable_frames`

- blog/content/edition-2/posts/10-heap-allocation/index.md
Removes the unused imports of serial_print/ln from heap allocation example code
> remove unused import

- blog/static/css/edition-2/main.css
- blog/templates/macros.html
The layout of Home page had problem showing right-to-left texts so i fixed it.
Also tables in posts that are right-to-left had the same issue causing show them incorrectly.
> fix layout of right-to-left in homepage and tables

- blog/content/_index.ja.md
Translated the index page.
@JohnTitor please review it!
> Translate the index page to Japanese

- blog/content/edition-2/posts/03-vga-text-buffer/index.md
Added explicit note to specify `volatile` crate version `0.2.6`, since later versions produce an error.
> Added note to specify version 0.2.6 of volatile

- Cargo.lock
- Cargo.toml
See https://github.com/rust-osdev/x86_64/pull/230
> Update x86_64 dependency to v0.13.2 to fix nightly breakage

- src/allocator/fixed_size_block.rs
- src/lib.rs
The `const_in_array_repeat_expressions` feature was removed in https://github.com/rust-lang/rust/pull/80404 because its design led to various bugs. The inline const blocks (`const { ... }`) feature should be a good alternative, but it is still marked as incomplete because there are still major bugs with it too. For this reason, this PR uses a local `EMPTY` constant instead to not require any unstable features at all.
> Use constant instead of removed `const_in_array_repeat_expressions` feature

- src/task/executor.rs
Fixes https://github.com/phil-opp/blog_os/issues/889.
> The `enable_interrupts_and_hlt` function was renamed to `enable_and_hlt`

- blog/content/edition-2/posts/04-testing/index.fa.md
- blog/content/edition-2/posts/04-testing/index.ja.md
- blog/content/edition-2/posts/04-testing/index.md
- blog/content/edition-2/posts/05-cpu-exceptions/index.fa.md
- blog/content/edition-2/posts/05-cpu-exceptions/index.md
- blog/content/edition-2/posts/06-double-faults/index.fa.md
- blog/content/edition-2/posts/06-double-faults/index.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.fa.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.md
- blog/content/edition-2/posts/08-paging-introduction/index.fa.md
- blog/content/edition-2/posts/08-paging-introduction/index.md
- blog/content/edition-2/posts/09-paging-implementation/index.md
- blog/content/edition-2/posts/10-heap-allocation/index.md
- blog/content/edition-2/posts/11-allocator-designs/index.md
- blog/content/edition-2/posts/12-async-await/index.md
This adjust the blog posts for the code updates implemented in https://github.com/phil-opp/blog_os/pull/919, https://github.com/phil-opp/blog_os/pull/921, and https://github.com/phil-opp/blog_os/pull/922.
Fixes #889
> Update post to use x86_64 v0.13.2

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
The referenced issue in compiler-builtins (https://github.com/rust-lang/compiler-builtins/pull/365) has been merged. Hence, I think it's safe to remove the note about the memory implementations not being optimized.
I'm not sure if you would want to state that the implementations are optimized - I think it's likely assumed by the reader unless otherwise stated.
> Remove note on builtin memory optimizations

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
Same as #932.
cc: @woodyZootopia or @JohnTitor
> chore(ja): remove the description about the memory optimizations

- blog/content/edition-2/posts/09-paging-implementation/index.md
Earlier in [02-minimal-rust-kernel/index.md](https://github.com/phil-opp/blog_os/blob/master/blog/content/edition-2/posts/02-minimal-rust-kernel/index.md) `bootloader = "0.9.8"` and here we are effectively downgrading to `bootloader = "0.9.3"` (Maybe there is an earlier feature that has been dropped that I am unaware of.)
> Inconsistent version and grammar change

- blog/content/edition-2/posts/09-paging-implementation/index.md
`error[E0252]: the name 'VirtAddr' is defined multiple times`
> x86_64::VirtAddr already imported on L415

- blog/content/edition-2/posts/12-async-await/index.md
Previously, in https://os.phil-opp.com/testing/ we set the dependency to `x86_64 = "0.13.2"` so this advice seems redundant.
> Previously updated dependency

- blog/content/edition-2/posts/12-async-await/index.md
You probably know: `wake_trait` has been stable since 1.51.0 and no longer requires an attribute to enable
> wake_trait is now stable

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
I was confused on what the 'unstable' section of my .cargo/config.toml file should look like once I started getting linking errors when going through the third post. It turned out it was because I overwrote the previous 'unstable' configuration with the latter one. 
In other words, I thought we were to overwrite "build-std = ["core", "compiler_builtins"]" under the "unstable" config, with "build-std-features = ["compiler-builtins-mem"]" and NOT have both present. 
I think this makes it more clear that both are supposed to be present.
> Suggestion for .cargo/config.toml Explanation

- blog/content/edition-2/posts/11-allocator-designs/index.md
Issue https://github.com/rust-lang/rust/issues/68049 is now fixed!
So we can remove that part. It isn't on nightly currently but will come. [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1eca2c196142cd9060a157d1f296d8d1) for checking it.
> Remove wrong suggestion part

- Cargo.lock
- Cargo.toml
- src/interrupts.rs
- tests/stack_overflow.rs
Builds upon https://github.com/phil-opp/blog_os/pull/988
> Update `linked_list_allocator` to v0.9.0

- Cargo.lock
- Cargo.toml
> Update x86_64 dependency to v0.14.2 to fix nightly breakage

- blog/content/edition-2/posts/04-testing/index.md
- blog/content/edition-2/posts/05-cpu-exceptions/index.md
- blog/content/edition-2/posts/06-double-faults/index.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.md
- blog/content/edition-2/posts/08-paging-introduction/index.md
- blog/content/edition-2/posts/09-paging-implementation/index.md
- blog/content/edition-2/posts/10-heap-allocation/index.md
- blog/content/edition-2/posts/11-allocator-designs/index.md
- blog/content/edition-2/posts/12-async-await/index.md
This implements the following three dependency updates to fix the build on the latest Rust nightlies:
- **`x86_64` from 0.13.2 to 0.14.2:** This includes some [breaking changes](https://github.com/rust-osdev/x86_64/pull/242) around the `x86-interrupt` calling convention, which requires changing the `&mut InterruptStackFrame` parameters in interrupt handler functions to `InterruptStackFrame` parameters (by-value instead of by-reference).
- **From `pic8259_simple` v0.2.0 to `pic8259` v0.10.0:** The original crate seems to be no longer maintained, but changes in Rust nightly require adjustments. For this reason, we forked the crate as [`pic8259`](https://github.com/rust-osdev/pic8259). Apart from adjusting the crate name and version number, no changes should be necessary.
- …
> Update posts to fix build on latest nightly

- blog/static/css/edition-2/main.css
- blog/templates/edition-2/base.html
- blog/templates/edition-2/extra.html
- blog/templates/edition-2/page.html
- blog/templates/news-page.html
- blog/templates/snippets.html
- blog/templates/status-update-page.html
To use GitHub discussions instead of issues for comment threads.
Requires migrating all comment threads to discussions.
> Switch comments from utterances to giscus

- blog/templates/edition-2/base.html
- blog/templates/edition-2/extra.html
- blog/templates/edition-2/page.html
- blog/templates/news-page.html
- blog/templates/snippets.html
- blog/templates/status-update-page.html
This makes us more flexible and gives us ways to avoid title collisions (e.g. when the title on an extra post is a substring of some post title).
> giscus: Use specific search term instead of `og:title`

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fa.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
Closes #1027
Cleans indentation to be consistent.
> docs: clean indent of JSONs

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
`rerun the our build command` -> `rerun our build command`
> Fix typo in `02-minimal-rust-kernel`

- blog/content/edition-2/posts/06-double-faults/index.md
set_cs is deprecated and CS::set_reg is preferred. Update the blog to reflect this change according to the docs.
> Set CS register with non-deprecated function

- blog/content/edition-2/posts/12-async-await/index.ja.md
Unnecessary parentheses were removed.
Before change
```
*self = ExampleStateMachine::End(EndState));
```
After change
```
*self = ExampleStateMachine::End(EndState);
```
> Delete unnecessary brackets

- blog/config.toml
- blog/sass/css/edition-2/main.scss
- blog/templates/edition-2/page.html
This field should list people that contributed to the translation, e.g. by fixing errors. The idea behind this field is to properly acknowledge all contributors, while still keeping the list of the original translation authors separate.
This PR is the result of a discussion in https://github.com/phil-opp/blog_os/pull/1108#issuecomment-1131676466.
(The commit adds a new translation string named `translation_contributors`, which is set to "With contributions from" initially for all languages. We should translate this string properly when we start using the new field for a language.)
> Add a new `translation_contributors` front matter field

- blog/content/edition-2/posts/12-async-await/index.ja.md
Merge #1108 and use new translation contributors field introduced in https://github.com/phil-opp/blog_os/pull/1112.
@Foo-x I also added you to the new contributors list because you contributed to this translation in the past. I hope this is ok with you.
> Merge correction for Japanese translation of post-12 and use `translation_contributors` field

- blog/content/edition-2/posts/12-async-await/index.ja.md
The following Japanese has been corrected because it has a different meaning.
Before change
```
コンパイラに `Unpin` を【選択】させることで、
```
After change
```
コンパイラに `Unpin` を【オプトアウト】させることで、
```
> Correction of Japanese

- blog/templates/edition-2/extra.html
- blog/templates/edition-2/page.html
- blog/templates/news-page.html
- blog/templates/snippets.html
- blog/templates/status-update-page.html
Avoids that a search for the post title returns a thread for a translated post.
> Move comment threads for translated posts to separate category

- blog/templates/edition-1/base.html
- blog/templates/edition-2/base.html
This commit removes the https://www.goatcounter.com/ script that we were using for basic, privacy-friendly analytics. I don't really need that data, so there is not much value in keeping it.
> Remove goatcounter analytics again

- blog/templates/edition-2/extra.html
- blog/templates/edition-2/page.html
- blog/templates/news-page.html
- blog/templates/snippets.html
- blog/templates/status-update-page.html
The giscus comment system is already translated to a variety of languages. We just need to set the `data-lang` tag accordingly.
> Translate the giscus comment system

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.fr.md
I found 2 typos in the french translation and fixed them.
> Fix typo in french translation 01-freestanding-rust-binary

- blog/content/edition-2/posts/09-paging-implementation/index.md
Fixes bad image URL in post-09 paging implementation/address-calculation section as detailed in: https://github.com/phil-opp/blog_os/issues/1145
> Fixes bad URL from post-09 address calculation section

- .github/workflows/blog.yml
- .github/workflows/check-links.yml
The job often fails temporarily, which can be confusing to contributors. By moving it to a separate 'Check Links' workflow, it hopefully becomes clearer that the failure is unrelated to a PR.
> CI: Move link check to separate workflow

- .github/workflows/check-links.yml
- blog/config.toml
- blog/content/edition-1/posts/03-set-up-rust/index.md
- Disable anchor checking for Japanese Rust edition guide
- Remove dead link from first edition
> Fix dead links

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
The command to run QEMU produces an output, but the output and
its message is not needed to complete the tutorial.
> Remove warning output from QEMU command.

- blog/.gitignore
Make git ignore 'zola' when contributors locally
build & test the blog with `./zola serve`.
Meant to be a small usability improvement for contributors.
> Add `zola` to `blog/.gitignore`

- .github/workflows/blog.yml
- .github/workflows/check-links.yml
- blog/config.toml
Updates the blog to the latest version of the [`zola`](https://www.getzola.org/) static site generator.
Changes since the previous version (0.16.1):
- Fix one more invalid error with colocated directories
- Revert "Recognize links starting with `www` as external for the link checker" as they won't be external links in practice
- Use page.summary for atom.xml if available
- Fix cachebusting not working with binary files
- Fix warning message for multilingual sites
- Fix bugs with colocated directories in the root `content` directory
- Fix `zola serve` not  respecting `preserve_dotfiles_in_output`
- Add `generate_feed` field to the `section` object in templates
- `get_file_hash` is removed, use `get_hash` instead. Arguments do not change
- Replace libsass by a Rust implementation: …
> Update `zola` to `v0.17.2`

- src/lib.rs
Allocation errors now always panic.
See:
- https://github.com/rust-lang/rust/pull/102318
- https://github.com/rust-lang/rust/pull/109507
> The `#[alloc_error_handler]` attribute was removed

- blog/content/edition-2/posts/10-heap-allocation/index.md
The unstable feature was removed. Allocation errors are reported as normal panics now.
See also the code update in #1216 .
> Update 'Heap Allocation' post to remove `alloc_error_handler`

- blog/content/edition-2/posts/06-double-faults/index.fa.md
- blog/content/edition-2/posts/06-double-faults/index.ja.md
- blog/content/edition-2/posts/06-double-faults/index.ko.md
- blog/content/edition-2/posts/06-double-faults/index.md
- blog/content/edition-2/posts/06-double-faults/index.zh-CN.md
- blog/content/edition-2/posts/08-paging-introduction/index.fa.md
- blog/content/edition-2/posts/08-paging-introduction/index.ja.md
- blog/content/edition-2/posts/08-paging-introduction/index.md
- blog/content/edition-2/posts/08-paging-introduction/index.zh-CN.md
**EDIT 2023-05-31:**
I just noticed that post 8 is affected by this as well (as already discussed in #1215) and applied the same fix there.
___
In the "Double Faults" post, the following code is given as an example:
```Rust
// trigger a page fault
unsafe {
*(0xdeadbeef as *mut u64) = 42;
};
```
Dereferencing `0xdeadbeef` as any type larger than `u8` is [undefined behavior](https://doc.rust-lang.org/reference/behavior-considered-undefined.html), and [a recently merged PR for Rust](https://github.com/rust-lang/rust/pull/98112) added runtime debug assertions for this.
Thus, instead of the desired effects, the above code panics with the message `'misaligned pointer dereference: address must be a multiple of 0x8 but is 0xdeadbeef'`.
Fortunately, the author chose the value `42` such that it …
> Fix panics caused by misaligned pointer dereferences in "Double Faults" & "Introduction to Paging"

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.fr.md
This PR improves the consistency of the French translation in Post 1 by changing the term ‘autonome’ to ‘autoporté’.
Additionally, it corrects a typo and an error for ‘Bien sûr’.
This PR also includes a reformulation of a sentence for improved clarity.
> Correcting typos and errors in French translation of Post 1

- blog/content/edition-2/posts/06-double-faults/index.md
The code segment from the example uses the newer function whilst the text segment refers to the old/deprecated `set_cs` fn. Let's fix that.
Note: that the method reference link points to docs 0.14.5 and not 0.14.2. It looks like it doesn't exist in the older version (?).
> posts/06-double-faults/index: fixup deprecated fn

- blog/templates/snippets.html
The category ID is used for creating new discussion threads if required. We forgot to adjust it for translated posts, so they ended up in the wrong category. This in turn caused issues such as https://github.com/phil-opp/blog_os/discussions/1214#discussioncomment-5953024.
> Fix: Use correct category ID for comment threads of translated posts

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
As a relatively new person to Rust, I confused the `.cargo/config.toml` with the global cargo config in my home directory (`~/.cargo/config.toml). While this is pretty obviously wrong in hindsight, since I've never used the `[unstable]` options before, I didn't realize my mistake until this next thing that tripped me up.
For `cargo install bootimage`, I think it is reasonable to tell the reader to go into a different directory to execute the command, since it might be the case that the reader has never dealt with different targets before and would have no idea that running `cargo install` for the new target that they just made in a json would be wrong (at least this was me).
This could be worded differently than the changes I made, but I think that the addition of these could only benefit …
> Update post 2 with beginner friendly cargo tips

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
> minimal-rust-kernel: fix missing .toml in zh-CN translation

- blog/templates/snippets.html
Reduces the number of false positives in search.
Reported in https://github.com/phil-opp/blog_os/discussions/999#discussioncomment-4086576
> Add `in:title` qualifier for discussion links

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/03-vga-text-buffer/index.ja.md
- blog/content/edition-2/posts/04-testing/index.ja.md
- blog/content/edition-2/posts/05-cpu-exceptions/index.ja.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
- blog/content/edition-2/posts/08-paging-introduction/index.ja.md
- blog/content/edition-2/posts/09-paging-implementation/index.ja.md
- blog/content/edition-2/posts/10-heap-allocation/index.ja.md
- blog/content/edition-2/posts/11-allocator-designs/index.ja.md
- blog/content/edition-2/posts/12-async-await/index.ja.md
I changed my GitHub ID from `woodyZootopia` to `swnakamura` recently. This commit just changes the `translators` section of the articles I took part in translation accordingly.
> Change one of translator's github ID

- blog/content/edition-2/posts/04-testing/index.fa.md
- blog/content/edition-2/posts/04-testing/index.ja.md
- blog/content/edition-2/posts/04-testing/index.md
- blog/content/edition-2/posts/04-testing/index.zh-CN.md
I always got the following error message when I tried chapter 4:
```rust
error[E0463]: can't find crate for `test`
For more information about this error, try `rustc --explain E0463`.
error: could not compile `os` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```
After comparing your source code on branch `post_04` with my code, I found out that the issue was function signature of `test_runner`: My signature was without `pub`. Adding the `pub` fixed it for me.
**HINT:** I don't really know if this PR is "necessary" because I couldn't find anyone else in the comments who got the same problem. Could it be that it just happened on my machine?
Greetings from Kerlsruhe by the way :)
> Adding fix to make the test_runner functions pub

- blog/content/edition-1/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/edition-1/posts/03-set-up-rust/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fa.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fr.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
The data layout changed in LLVM. Using the wrong data layout now leads to a build error (since See https://github.com/rust-lang/rust/pull/120062).
The `post-X` branches were already updated.
> Update data layouts in target specifications

- blog/content/edition-1/extra/set-up-gdb/index.md
Some websites still link to the old `.html` URL.
Fixes #1305
> Add `.html` alias to 'Set Up GDB' post

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
Newer versions use a different build system and will result in build errors when following the post.
> Add a note that only `bootloader v0.9` is compatible

- blog/content/edition-2/posts/07-hardware-interrupts/index.fa.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.ja.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.ko.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.zh-CN.md
- blog/content/edition-2/posts/12-async-await/index.ja.md
- blog/content/edition-2/posts/12-async-await/index.md
crossbeam and pc_keyboard have had breaking changes, I figured it'd be helpful to keep them up-to-date in the blog so if people want to use the latest versions they won't get stuck. Also, it's my first time doing a pull request and I think I messed up so I closed the old one, my apologies if I did something wrong.
> Update crossbeam and pc_keyboard

- blog/content/edition-3/posts/03-screen-output/index.md
Giving the posts another read as I'm on a new machine and want to pick up where I left off, might make more PRs of this nature depending on what I notice
> Move import to sensible location in chapter 3

- blog/content/edition-2/posts/04-testing/index.md
`panic-abort-tests = true` will, as described by the [cargo unstable features docs](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#panic-abort-tests), enable nightly support to compile test harness crates with `-Cpanic=abort`. Without this flag Cargo will compile tests, and everything they depend on, with `-Cpanic=unwind` because it’s the only way test-the-crate knows how to operate.
This fixed my compilation issues that were not solved by the other suggested workaround.
> 04-testing: Added panic-abort-tests flag note to "duplicate lang item" workaround

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
Added/corrected the explanation for why the new target still uses Linux conventions
> Update post 02 "Building our Kernel" section

- blog/content/edition-2/posts/03-vga-text-buffer/index.md
Tiny PR adding return type `!` to `_start()` under the "Hello World using println" section, to make it consistent with the other two times `_start()` appears in the blog post.
> add return type on `_start()` in code block

- blog/content/edition-2/posts/11-allocator-designs/index.ja.md
- blog/content/edition-2/posts/11-allocator-designs/index.md
Fixes https://github.com/phil-opp/blog_os/issues/1370
> The `const_mut_refs` feature is stable now and no longer required

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fa.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fr.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
The Rust compiler now requires an explicit `rustc-abi: x86-softfloat` field when using the soft-float target feature. This was added in https://github.com/rust-lang/rust/pull/136146 and is part of the latest nightlies.
I updated the post branches in commit 688a21e4
> Add `rustc-abi` field to target spec JSON

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fa.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fr.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
Post 02 currently states...
> As we want to use the `soft-float` feature, we also need to tell the Rust compiler `rustc` that we want to use the corresponding ABI. We can do that by setting the `x86-softfloat` field to `x86-softfloat`.
...when the field name should be `rustc-abi`.
I've updated this for all localizations.
> Fix typo when referencing the `rustc-abi` field.

- blog/content/edition-2/posts/09-paging-implementation/index.md
There's a missing '&' in [some code snippet](https://github.com/phil-opp/blog_os/blob/98f616964da8eb04fa76998be739431016904254/blog/content/edition-2/posts/09-paging-implementation/index.md?plain=1#L402) of post 09. I added it.
> Fix the missing '&' in post 09

- blog/content/edition-3/posts/02-booting/index.md
Update [02-booting/index.md](https://github.com/phil-opp/blog_os/blob/edition-3/blog/content/edition-3/posts/02-booting/index.md) to replace `-bios=OVMF-pure-efi.fd` with proper UEFI setup using `OVMF_CODE.fd` and `OVMF_VARS.fd` via `-drive if=pflash`, using `ovmf_prebuilt = 0.2.3`.
> loading UEFI using ovmf_prebuilt=0.2.3 with ovmf_code and ovmf_vars

- x86_64-blog_os.json
Fixes the build on latest Rust nightlies.
> Fix: `target-c-int-width` field now expects an integer
