- src/lib.rs
Avoid special core features and complicated iterator chaining to make the code simpler overall.
> Improve `Hello World!` code

- Makefile
- src/arch/x86_64/grub.cfg
> Makefile fixes 

- src/arch/x86_64/linker.ld
- src/arch/x86_64/multiboot_header.asm
> Rename `multiboot` section to `multiboot_header`

- src/arch/x86_64/boot.asm
1 GiB pages are a relatively new feature, Intel introduced it in 2010 and QEMU in 2014. So we don't want to rely on it and make the whole OS incompatible to older systems. See issue #17.
> Use 2MiB pages instead of one 1GiB page

- pages/cross-compile-binutils.md
- pages/cross-compile-libcore.md
- posts/2015-08-18-multiboot-kernel.md
- posts/2015-08-25-entering-longmode.md
- posts/2015-09-02-setup-rust.md
- posts/2015-10-23-printing-to-screen.md
For history see the `rust_os_posts` tag in the [phil-opp/phil-opp.github.io](https://github.com/phil-opp/phil-opp.github.io) repository.
> Move blog posts/pages into code repository

- Cargo.toml
- posts/2015-09-02-setup-rust.md
- posts/2015-10-23-printing-to-screen.md
> Replace wildcards in dependencies with a lower bound

- posts/2015-09-02-setup-rust.md
> Mention `-C no-redzone` in the `Setup Rust` post

- posts/2015-11-15-allocating-frames.md
Explain the disadvantages of creating a data structure and add motivation for using Multiboot's memory map. Also, outline how to solve the problem of freeing frames.
> Discuss alternative frame stack designs

- posts/2015-09-02-setup-rust.md
> Recommend `multirust override nighly`

- posts/2015-08-18-multiboot-kernel.md
> Add a note about Mac OS and virtual machines

- posts/2015-09-02-setup-rust.md
- src/arch/x86_64/boot.asm
- src/arch/x86_64/long_mode_init.asm
> Move `setup_SSE` to boot.asm

- posts/2015-12-09-modifying-page-tables.md
> Change title to `Page Tables`

- posts/2015-12-09-modifying-page-tables.md
> Add a link to the x86 crate

- posts/2015-12-09-modifying-page-tables.md
- src/memory/paging/table.rs
> Fix HierachicalLevel typo (rebased)

- posts/2015-12-09-modifying-page-tables.md
- src/memory/paging/mod.rs
> Rename RecursivePageTable to ActivePageTable

- posts/2015-12-09-modifying-page-tables.md
Also, improve headings and the ActivePageTable section a bit.
> Explain lifetime elision in `next_table` methods

- posts/2015-09-02-set-up-rust.md
> Use new example code to cause SSE failure

- posts/2015-12-09-modifying-page-tables.md
This brings it in line with the code.
> Make Page::containing address public in post

- Makefile
- posts/2016-01-01-remap-the-kernel.md
- src/arch/x86_64/linker.ld
- src/lib.rs
- src/memory/mod.rs
- src/memory/paging/entry.rs
- src/memory/paging/mapper.rs
- src/memory/paging/mod.rs
- src/memory/paging/table.rs
- src/memory/paging/temporary_page.rs
[(Poorly) rendered](https://github.com/phil-opp/blog_os/blob/remap-the-kernel/posts/2016-01-01-remap-the-kernel.md)
> New post about remapping the kernel

- posts/2015-08-25-entering-longmode.md
- src/arch/x86_64/boot.asm
New comments by @henrikhodne from #98
> Improve comments for CPUID check

- posts/2015-10-23-printing-to-screen.md
> Add missing brackets

- posts/2015-12-09-modifying-page-tables.md
[Reported by FreeFull](http://os.phil-opp.com/modifying-page-tables.html#comment-2466158032)
> Fix type name: `EntryFlags` instead of `TableEntryFlags`

- _sass/_masthead.scss
- index.html
Add a small introduction to the front page.
Feedback appreciated!
Fixes #109
> Add an introduction to the front page

- posts/2015-08-18-multiboot-kernel.md
> Add grub-mkrescue troubleshooting steps

- posts/2015-12-09-modifying-page-tables.md
> Fix type name: `Entry` instead of `EntryFlags`

- posts/2015-09-02-set-up-rust.md
> Link travis build and note that the code works for the newest nightly

- posts/2015-08-25-entering-longmode.md
- src/arch/x86_64/boot.asm
> Add/extend explanations in Entering Longmode

- posts/2015-10-23-printing-to-screen.md
This addresses various issues reported in #98 
cc @mtnygard (I would appreciate a quick feedback)
Closes #98
> Improve Printing to Screen post

- posts/2015-11-15-allocating-frames.md
cc @Ketsuban (do you think it's better now?)
Closes #116
> Improve introduction for frame allocation and explain what a frame is

- posts/2015-10-23-printing-to-screen.md
> Add `#[allow(dead_code)]` to Color enum

- posts/2015-12-09-modifying-page-tables.md
- src/memory/paging/table.rs
> Make some more types public since they are part of the public interface

- posts/2016-04-11-kernel-heap.md
Fixes #144 
cc @DSMan195276 (thanks again for your detailed comments on /r/rust)
> Remove wrong claims about the linux allocator

- .travis.yml
- scripts/travis-blog-update.sh
- scripts/travis-build.sh
This PR completes the migration to [hugo](https://gohugo.io).
> Build hugo blog using travis

- blog/post/2015-09-02-set-up-rust.md
Reported [by Erdos](http://os.phil-opp.com/set-up-rust.html#comment-2653191151).
> The no-landing-pads snippet already generates SSE instructions

- blog/post/2015-10-23-printing-to-screen.md
[Reported by Nathan](http://os.phil-opp.com/printing-to-screen.html#comment-2657686511)
> Add missing `mut` in print! implementation

- layouts/index.html
- static/css/main.css
> Add new “interrupts” section to index page

- layouts/index.html
> Render additional resources at the end of index.html

- blog/post/2016-05-28-catching-exceptions.md
> Add missing link to bit_field crate

- blog/post/2015-09-02-set-up-rust.md
- src/lib.rs
> Create dummy _Unwind_Resume function to fix libcore linker errors

- README.md
> Add gitter chat badge to README

- blog/post/2015-08-18-multiboot-kernel.md
- blog/post/2015-08-25-entering-longmode.md
- blog/post/2015-09-02-set-up-rust.md
- blog/post/2015-10-23-printing-to-screen.md
- blog/post/2015-11-15-allocating-frames.md
- blog/post/2015-12-09-modifying-page-tables.md
- blog/post/2016-01-01-remap-the-kernel.md
- blog/post/2016-04-11-kernel-heap.md
- blog/post/2016-05-28-catching-exceptions.md
This adds the empty toc asides, which are filled by the #191.
> Add tables of contents to all blog posts

- blog/post/2016-08-03-better-exception-messages.md
- src/interrupts/mod.rs
> Fix clobber syntax and add missing rsi clobber in code

- Cargo.toml
- blog/post/2016-05-28-catching-exceptions.md
- src/lib.rs
> Use upstream lazy_static and upgrade `once` to latest version

- Cargo.toml
- blog/post/2016-04-11-kernel-heap.md
> Create a cargo workspace for subcrates

- README.md
I had to add `mtools` on Arch.
> Add mtools to readme

- blog/additional-resource/cross-compile-libcore.md
- blog/post/03-set-up-rust.md
> Use rustup for cross compiling and also explain xargo

- Cargo.toml
- blog/post/09-catching-exceptions.md
- src/interrupts/idt.rs
> Update bit_field to 0.5.0 and use new trait based API

- Cargo.toml
- blog/post/05-allocating-frames.md
> Use crates.io version of multiboot2

- Makefile
- src/arch/x86_64/boot.asm
- src/arch/x86_64/grub.cfg
- src/arch/x86_64/linker.ld
- src/arch/x86_64/long_mode_init.asm
- src/arch/x86_64/multiboot_header.asm
- src/interrupts/idt.rs
- src/interrupts/mod.rs
- src/lib.rs
- src/memory/area_frame_allocator.rs
- src/memory/mod.rs
- src/memory/paging/entry.rs
- src/memory/paging/mapper.rs
- src/memory/paging/mod.rs
- src/memory/paging/table.rs
- src/memory/paging/temporary_page.rs
- src/vga_buffer.rs
> Add missing license headers and update copyright year

- codegen/src/main.rs
It makes no sense to output “x minutes ago” since we're only building the blog once per day.
Maybe we can reproduce the old behavior via javascript.
> Use absolute times instead of durations in “Recent Updates”

- blog/post/10-better-exception-messages.md
Yesterday Hoschi reported the following problem in [a comment](http://os.phil-opp.com/better-exception-messages.html#comment-2945571749) on the blog:
> I am stuck with #reproducing-the-bug-in-qemu. I cannot reproduce the alignment issue, neither in QEMU (with -enable-kvm) nor on real hardware.
I'm not quite sure what's causing this, but I can no longer reproduce the triple fault either. It _could_ be caused by our recent update of the VGA driver, which introduces volatile writes. Or it's just some codegen change in Rust/LLVM…
This PR expands the post with some example code that compiles to `movaps` instructions. Thus, the kernel should triple fault on real hardware again.
> Better Exception Messages: Add example code that triggers the triple fault on real hardware again

- blog/post/07-remap-the-kernel.md
> Wording: therefor -> for that

- blog/post/02-entering-longmode.md
> Minor grammatical error fix

- Cargo.toml
> Remove cargo workspace

- blog/post/08-kernel-heap.md
> Remove workspace from post too

- Cargo.toml
- blog/post/06-page-tables.md
- blog/post/07-remap-the-kernel.md
- blog/post/09-catching-exceptions.md
- blog/post/10-better-exception-messages.md
- src/interrupts/idt.rs
- src/interrupts/mod.rs
- src/lib.rs
- src/memory/paging/mapper.rs
- src/memory/paging/mod.rs
> Update x86 crate to version 0.8.0

- blog/post/03-set-up-rust.md
- blog/post/05-allocating-frames.md
- src/lib.rs
> Make panic_fmt public to fix private_no_mangle_fns warning

- src/arch/x86_64/boot.asm
> The ReadWrite flag isn't needed for code segments

- Cargo.toml
- blog/post/09-catching-exceptions.md
- blog/post/12-double-faults.md
- src/interrupts/gdt.rs
- src/interrupts/idt.rs
> Update to latest bit_field version

- blog/content/post/09-handling-exceptions.md
Reported by `youstolemyname` [on /r/rust](https://www.reddit.com/r/rust/comments/61l5hx/writing_an_os_in_rust_handling_exceptions/dfg0sr0/).
> Remove duplicate word

- blog/content/post/09-handling-exceptions.md
> Mention that we need to enable the abi_x86_interrupt feature

- .travis.yml
> Fix CI by avoiding duplicate rustup installation

- blog/content/posts/01-multiboot-kernel/index.md
This change to 01-multiboot-kernel/index.md fixes issue #337
> Explain and motivate "ISO"

- blog/content/posts/01-multiboot-kernel/index.md
Garbled sentence, no word "everytime".
> Two minor English fixes

- blog/content/posts/01-multiboot-kernel/index.md
> Minor error in 01-multiboot-kernel.md

- Cargo.toml
- blog/content/extra/naked-exceptions/02-better-exception-messages/index.md
- blog/content/extra/naked-exceptions/03-returning-from-exceptions/index.md
- blog/content/posts/06-page-tables/index.md
- blog/content/posts/10-double-faults/index.md
- src/interrupts/gdt.rs
- src/memory/paging/entry.rs
Update bitflags from 0.7.0 to 0.9.1.
Ref: #344
> Update bitflags to 0.9.1

- blog/content/posts/04-printing-to-screen/index.md
- blog/content/posts/06-page-tables/index.md
- src/memory/paging/mapper.rs
- src/vga_buffer.rs
Change Unique to use `new_unchecked`. Fixes #345.
> Use new Unique API

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
Some minor corrections while proof-reading.
Changed Max OS X to macOS, since it's the official Apple speak since 2016.
> Corrections from proof read for second edition first article

- blog/content/posts/03-set-up-rust/index.md
> Mention RUST_TARGET_PATH in Set Up Rust post (first edition)

- Cargo.toml
- blog/content/second-edition/posts/03-vga-text-buffer/index.md
- blog/content/second-edition/posts/04-unit-testing/index.md
- blog/templates/second-edition/index.html
- src/main.rs
- src/vga_buffer.rs
This is a small post about unit testing in `no_std` applications. It does not contain much operating system related content, but I think that a working `cargo test` is useful even in kernels. The post is also a good introduction for the next planned post, which will try to create a small integration test framework that runs tests inside QEMU.
[Rendered Preview](https://github.com/phil-opp/blog_os/blob/unit-tests/blog/content/second-edition/posts/04-unit-testing/index.md)
Feedback appreciated!
> Create a new post about unit testing

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
I found the "even" in this sentence to be confusing, so I changed it and modified the end of the sentence to avoid redundancy.
> Fix confusing wording

- blog/content/second-edition/posts/05-integration-tests/index.md
based on https://github.com/phil-opp/blog_os/issues/443#issuecomment-400625857 .
> explain choice of 0xf4 for I/O port

- blog/content/news/2018-03-09-pure-rust.md
This just contains a very minor re-word and a small adjustment.
> make text clearer

- blog/content/second-edition/posts/08-hardware-interrupts/index.md
- src/interrupts.rs
- src/lib.rs
- src/main.rs
This PR refactors the `hardware-interrupts` branch so it will match the re-write of the earlier posts from #475.
> refactor interrupts for #475

- blog/content/second-edition/posts/05-integration-tests/index.md
> Mention `cargo test --lib`

- blog/content/second-edition/posts/09-paging-introduction/index.md
Love this series and thought I'd contribute in whatever way I could. Thanks for the great work.
Looking forward to the next post!
> Fixing typos in paging introduction

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
Hi Phil, thanks a lot for these posts! I noticed some of the links are becoming outdated, so (if it's ok with you) I'll try to keep updating them and sending you PRs as I go through the posts.
> Fix old links in freestanding Rust bin post.

- blog/content/second-edition/posts/01-freestanding-rust-binary/index.md
- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
Thanks to https://github.com/phil-opp/blog_os/pull/550.
> The first post is now buildable on stable Rust

- blog/content/second-edition/posts/03-vga-text-buffer/index.md
BTW, thank you for your awesome post!
> fix typo: 'can used' -> 'can be used'

- blog/content/second-edition/posts/05-integration-tests/index.md
- blog/content/second-edition/posts/06-cpu-exceptions/index.md
- blog/content/second-edition/posts/07-double-faults/index.md
- blog/content/second-edition/posts/08-hardware-interrupts/index.md
- blog/content/second-edition/posts/09-paging-introduction/index.md
- blog/content/second-edition/posts/10-advanced-paging/index.md
A changelog can be found here: https://github.com/rust-osdev/x86_64/pull/61.
> Update to version 0.5.0 of x86_64

- src/main.rs
> Update post-09 branch for new "Paging Implementation" post

- azure-pipelines.yml
This is mostly a test PR for testing the new deploy process.
> Use requirements.txt for PyGitHub

- .appveyor.yml
- .cargo/config
- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- azure-pipelines.yml
This merges the changes of #585 into the `post-03` branch.
Blocked on #582.
> Merge the changes from #585 into the post-03 branch

- blog/content/second-edition/posts/09-paging-implementation/index.md
This pull request updates the `Paging Implementation` post for the new `BootInfoFrameAllocator` implementation in https://github.com/phil-opp/blog_os/pull/595.
> Update Paging Implementation for new frame allocator implementation

- Cargo.toml
Fixes #602 
Post update in https://github.com/phil-opp/blog_os/pull/605
> Use `-serial stdio` instead of `-serial mon:stdio`

- blog/content/status-update/2019-06-03.md
- blog/templates/status-update-page.html
This PR adds an "Updates in May 2019" post that gives an overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in May 2019

- blog/templates/second-edition/index.html
Adds the status updates link to the extra content section of the blog
> Add Status Updates Link

- Cargo.lock
- Cargo.toml
- README.md
- src/allocator.rs
- src/lib.rs
- src/main.rs
- tests/heap_allocation.rs
This adds the code updates for the new heap allocation post introduced in #625.
> Code for new heap allocation post

- blog/content/second-edition/posts/08-paging-introduction/index.md
I noticed two small typos while reading chapter 8.
> Introduction to Paging: fix a couple of small typos

- src/interrupts.rs
See https://github.com/phil-opp/blog_os/issues/513 for more information.
> The error code issue is fixed, so let's print it

- blog/content/second-edition/extra/disable-red-zone/index.md
Replace an adjective with an adverb.
> Fix grammar typo in "Red Zone"

- blog/content/status-update/2019-08-01.md
- blog/content/status-update/2019-08-02.md
This PR adds an "Updates in July 2019" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in July 2019

- blog/content/second-edition/posts/04-testing/index.md
Thanks for the excellent work!
> Fix typo in 04-testing

- blog/content/second-edition/posts/06-double-faults/index.md
Found a minor typo while following along.
Thank you for publishing this series, it's great!
> Fix minor typo

- blog/content/status-update/2019-09-09.md
This PR adds an "Updates in August 2019" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in August 2019

- src/main.rs
- src/memory.rs
This pull request adjusts the post-09 branch for the changes in #666.
> Update post-09 branch for improved Paging Implementation Post

- blog/content/status-update/2019-10-06.md
This PR adds an "Updates in September 2019" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in September 2019

- .github/workflows/build-code.yml
Don't fail if current nightly has no rustfmt
> Use latest nightly with rustfmt for formatting check

- blog/content/second-edition/posts/04-testing/index.md
> fixed repeated "the" typo

- blog/content/status-update/2019-12-02.md
This PR adds an "Updates in October and November 2019" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in October and November 2019

- Cargo.lock
- Cargo.toml
[x86_64 0.8.0 Changelog](https://github.com/rust-osdev/x86_64/blob/master/Changelog.md#080)
> Update to x86_64 0.8.0

- src/memory.rs
Update to x86_64 0.8.0 happened in #701.
> Update frame allocation code to x86_64 0.8.1

- blog/content/second-edition/posts/05-cpu-exceptions/index.md
We already updated the other posts in https://github.com/phil-opp/blog_os/pull/644 but forgot to update this post.
Reported by @GuillaumeDIDIER  in https://github.com/phil-opp/blog_os/issues/450#issuecomment-538722685.
> The LLVM error code bug was resolved

- blog/content/status-update/2020-01-07.md
This PR adds an _"Updates in December 2019"_ post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in December 2019

- blog/content/second-edition/posts/11-allocator-designs/index.md
Update _Allocator Designs_ post for changes in https://github.com/phil-opp/blog_os/pull/726.
> Update allocator designs post to use checked additions

- src/allocator.rs
Code update for https://github.com/phil-opp/blog_os/pull/721.
> Improve `align_up` performance using a bitmask

- blog/content/second-edition/posts/11-allocator-designs/index.md
This pull request adds two variants of the `align_up` function that use different approaches and shortly discusses their performance.
Inspired by https://github.com/phil-opp/blog_os/issues/720#issuecomment-576401348.
> Provide multiple implementations of align_up and mention performance

- blog/static/css/main.css
- blog/static/js/main.js
This introduces some Javascript to make the active item in the table of contents in the sidebar bold. This should make it easier to orient oneself in long posts.
> Mark active item in table of contents

- blog/static/css/main.css
> Make active section link more discreet

- blog/content/second-edition/posts/_index.zh-TW.md
- blog/templates/macros.html
- blog/templates/second-edition/index.html
Some followup fixes after merging #692.
> Some fixes to generated translations

- blog/content/second-edition/posts/08-paging-introduction/index.md
> Mention in "Paging Introduction" that a CPU with 5-level paging is available now

- blog/content/second-edition/posts/07-hardware-interrupts/index.md
> Hardware Interrupts: Update pc-keyboard crate to v0.5.0

- blog/content/status-update/2020-03-02.md
- blog/static/css/main.css
- blog/templates/status-update-page.html
This PR adds an "Updates in February 2020" post that gives a short overview of the recent changes to the blog and the tools/libraries behind the scenes.
> Updates in February 2020

- Cargo.lock
- Cargo.toml
This fixes compilation errors on recent nightlies. See https://github.com/phil-opp/linked-list-allocator/issues/24.
> Update linked_list_allocator to v0.8.0

- blog/content/second-edition/posts/12-async-await/index.md
> Fix typo 'compilicated'

- blog/content/second-edition/posts/12-async-await/index.md
Proposed in https://www.reddit.com/r/rust/comments/fq083y/writing_an_os_in_rust_asyncawait/flqd678/.
> Discuss the approach of storing offsets for self-referential structs

- blog/content/second-edition/posts/12-async-await/index.md
Updates the post to incorporate the changes from #782.
> Update Async/Await post for new task ID implementation

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.zh-CN.md
https://github.com/phil-opp/blog_os/issues/792#issuecomment-613253056
> Fix command line in Chinese translation of post 2.

- blog/content/second-edition/posts/02-minimal-rust-kernel/index.md
I just happened upon this tiny typo in post #2 so I thought I'd make a PR for it!
No biggie, thanks for the great tutorials!
> Fix a tiny typo

- blog/content/second-edition/posts/12-async-await/index.md
Update post for changes introduced in https://github.com/phil-opp/blog_os/pull/804.
> Update Async/Await post for simplified executor design

- blog/content/second-edition/posts/07-hardware-interrupts/index.md
Fixes #807 
Code update in 93b96f21acac4711a65d6309f496809d38623c3a.
> Update Hardware Interrupts post to use pic8259_simple v0.2.0

- blog/content/second-edition/posts/04-testing/index.md
Updates the post for the changes in https://github.com/phil-opp/blog_os/pull/816.
> Update Testing post to use Testable trait for automatic printing

- src/lib.rs
- src/main.rs
- src/vga_buffer.rs
- tests/basic_boot.rs
- tests/should_panic.rs
Suggested by @zzmp in https://github.com/phil-opp/blog_os/issues/591#issuecomment-637053801﻿
> Create a testable trait for printing test messages automatically

- blog/content/second-edition/posts/04-testing/index.md
- blog/content/second-edition/posts/05-cpu-exceptions/index.md
- blog/content/second-edition/posts/06-double-faults/index.md
- blog/content/second-edition/posts/07-hardware-interrupts/index.md
- blog/content/second-edition/posts/08-paging-introduction/index.md
- blog/content/second-edition/posts/09-paging-implementation/index.md
- blog/content/second-edition/posts/10-heap-allocation/index.md
- blog/content/second-edition/posts/12-async-await/index.md
Update blog posts for code update in https://github.com/phil-opp/blog_os/pull/858.
> Update blog posts to x86_64 v0.12.1

- blog/static/js/main.js
- blog/templates/second-edition/index.html
- blog/templates/second-edition/page.html
Not just languages enabled in the browser. This makes the translations more discoverable.
Fixes #879
> Show all available languages

- blog/content/edition-2/posts/06-double-faults/index.md
I found some minor issue in post 6. Could you review them?
> minor fix in post 6

- blog/content/edition-2/posts/06-double-faults/index.md
I think this is missing a preposition. (Sorry for targeting the wrong branch before.)
> minor typo

- blog/content/edition-2/posts/12-async-await/index.md
minor omission of a definite article.
> missing word

- Cargo.lock
- Cargo.toml
- src/interrupts.rs
- tests/stack_overflow.rs
Builds upon https://github.com/phil-opp/blog_os/pull/985
> Adjust `post-06` for x86_64 v0.14

- Cargo.lock
- Cargo.toml
- src/interrupts.rs
Builds upon https://github.com/phil-opp/blog_os/pull/984
> Adjust `post-05` for x86_64 v0.14

- blog/content/edition-2/posts/04-testing/index.md
- blog/templates/edition-2/page.html
- blog/templates/snippets.html
Useful in case of conflicts (e.g. two posts with the same title).
> Make it possible to set discussion thread manually per post

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.ja.md
Refs #906
Fixes the link to the next post.
> docs: fix link to next post

- blog/content/edition-2/posts/12-async-await/index.ja.md
- blog/content/edition-2/posts/12-async-await/index.md
> docs: fix typo

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md
> Fix link typos for #1043

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.fr.md
Hi, just spotted those 2 mistakes in french while following the blog in french
> Fix french in 01-freestanding-rust-binary

- blog/config.toml
- blog/content/_index.ko.md
- blog/content/edition-2/posts/01-freestanding-rust-binary/index.ko.md
- blog/content/edition-2/posts/_index.ko.md
Hello :smiley_cat: , 
I finished translating the first post of the blog series to Korean.
I locally built the website with zola to see how the translated page is rendered.
I reviewed the translation several times to correct any mistakes.
Thank you for your hard work on this blog series :+1: :+1:
> Korean translation for ch-01

- blog/content/edition-2/posts/05-cpu-exceptions/index.md
I think you mean "voluntarily" here?
> Fix small typo

- src/gdt.rs
#1096 
Update the code in the `post-06` branch
> Update the code in the post-06 branch

- blog/content/edition-2/posts/02-minimal-rust-kernel/disable-red-zone/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/disable-simd/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
Locally checked rendering using `zola` :smiley_cat:
> Korean translation for chapter 2

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
@Quqqu helped with reviewing Korean translation drafts for
post-01 & post-02.
> Add @Quqqu to Korean translators' list: post 1 & 2

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/disable-red-zone/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/disable-simd/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/03-vga-text-buffer/index.md
- blog/content/edition-2/posts/04-testing/index.md
- blog/content/edition-2/posts/05-cpu-exceptions/index.md
- blog/content/edition-2/posts/06-double-faults/index.md
- blog/content/edition-2/posts/07-hardware-interrupts/index.md
- blog/content/edition-2/posts/08-paging-introduction/index.md
- blog/content/edition-2/posts/09-paging-implementation/index.md
- blog/content/edition-2/posts/10-heap-allocation/index.md
- blog/content/edition-2/posts/11-allocator-designs/index.md
- blog/content/edition-2/posts/12-async-await/index.ja.md
- blog/content/edition-2/posts/12-async-await/index.md
This fixes grammar, punctuation, etc. and clarifies some sentences.
I'm keeping this as a draft for now, but I want to help out a lot more. If you want, I can also split every writing check into its own PR, but I'm trying to stay conservative with the changes.
I'm using my common sense and, in some places, grammar checkers.
> Check writing of all posts in edition 2

- blog/config.toml
- blog/templates/status-update-page.html
- Fix prev/next links for old status update posts
- Fix license file ignore
> Fixes for zola update

- blog/content/edition-2/posts/01-freestanding-rust-binary/index.fr.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fr.md
Hi,
as I [feared from the initial PR](https://github.com/phil-opp/blog_os/pull/1144#issuecomment-1278241807), there are a lot of broken/invalid links (mostly, the links and texts were swapped).
This PR should fix them (plus 2/3 minor changes).
I also translated the title of the first article.
nb: I had to setup a quick & dirty "docker-compose development environment" to be able to test. It's [there](https://github.com/alaincao/blog_os/commit/34d44e1eb4e32d38478f6bdf40ca6a43b819899a), if anyone is interested.
> French translation's links fixes

- blog/content/edition-1/extra/naked-exceptions/01-catching-exceptions/index.md
- blog/content/edition-1/posts/10-double-faults/index.md
- blog/content/edition-2/posts/04-testing/index.ja.md
- blog/content/edition-2/posts/06-double-faults/index.fa.md
- blog/content/edition-2/posts/06-double-faults/index.ja.md
- blog/content/edition-2/posts/06-double-faults/index.ko.md
- blog/content/edition-2/posts/06-double-faults/index.md
- blog/content/edition-2/posts/06-double-faults/index.zh-CN.md
Applies the link fixes by @kennystrawnmusic from #1187 on top of `main`.
> Fix broken links

- blog/content/edition-3/posts/03-screen-output/index.md
Feel free to add to this as you wish, but given how little activity there’s been on the third edition, I figured it’s time to use a PR to speed things up a bit.
> #1063: Submit rough draft of Edition-3-Post-3

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
Following #1234, on rereading this there was a grammar mistake
> Grammar fix

- blog/content/edition-2/posts/12-async-await/index.ja.md
- blog/content/edition-2/posts/12-async-await/index.md
> Fix: broken link of generator

- blog/content/edition-3/posts/03-screen-output/index.md
> fix a lil typo

- blog/content/edition-3/posts/03-screen-output/index.md
In addition to the other (self-explanatory) changes, `Display` now takes a reference to the `FrameBuffer` struct since we can't actually take ownership of it
> Fix `embedded_graphics` code + typo in chapter 3

- blog/config.toml
- blog/templates/edition-2/index.html
- blog/templates/edition-2/page.html
- blog/templates/snippets.html
Fixes https://github.com/phil-opp/blog_os/issues/1284
> Enable translations of the 'Support Me' section and the comment note

- .github/workflows/blog.yml
- .github/workflows/check-links.yml
- blog/config.toml
Changelog: https://github.com/getzola/zola/blob/master/CHANGELOG.md#0190-2024-06-20
> Update to zola v0.19

- Cargo.toml
...with test and bench set to false to prevent duplicate definition of lang item
> Added [[bin]] section to Cargo.toml

- blog/content/edition-2/posts/10-heap-allocation/index.zh-CN.md
I've submitted the Chinese version of "Heap Allocation". Beyond the markdown document, are there any other modifications I should make?
> Heap allocation chinese translation

- blog/content/edition-2/posts/02-minimal-rust-kernel/index.es.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fa.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.fr.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ja.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ko.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.ru.md
- blog/content/edition-2/posts/02-minimal-rust-kernel/index.zh-CN.md
> Update blog for `target-c-int-width` change
